/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0 (GUI_ID_USER + 0x01)
#define ID_TEXT_1 (GUI_ID_USER + 0x02)
#define ID_TEXT_2 (GUI_ID_USER + 0x03)
#define ID_TEXT_3 (GUI_ID_USER + 0x04)
#define ID_TEXT_4 (GUI_ID_USER + 0x05)
#define ID_TEXT_5 (GUI_ID_USER + 0x06)


#define ID_EDIT_0 (GUI_ID_USER + 0x07)
#define ID_EDIT_1 (GUI_ID_USER + 0x08)
#define ID_EDIT_2 (GUI_ID_USER + 0x09)
#define ID_EDIT_3 (GUI_ID_USER + 0x0A)


#define ID_BUTTON_0 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0D)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0E)



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER ENDconst char OperateCode[]

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "AdvanceSet",  ID_WINDOW_0, 0,   0,   240, 295, 0, 0x0,  0 },
  { TEXT_CreateIndirect,   ScrTimeout,      ID_TEXT_0,   12,  12,  120,  20,  0, 0x0,  0 },
  { TEXT_CreateIndirect,   ShutDownTime,   ID_TEXT_1,   12,  42,  120, 20,  0, 0x0,  0 },
  //{ TEXT_CreateIndirect,   ShutDownTime,  ID_TEXT_2,   12,  72,  100,  20,  0, 0x0,  0 },
  
  { EDIT_CreateIndirect,   "freq",        ID_EDIT_0,   130,   10,  100, 20,  0, 0x64, 0 },
  { EDIT_CreateIndirect,   "Opcode",      ID_EDIT_1,   130,   40,  100, 20,  0, 0x64, 0 },
  //{ EDIT_CreateIndirect,   "freq",        ID_EDIT_2,   111,  70,  120, 20,  0, 0x64, 0 },
  
  { BUTTON_CreateIndirect, Save,          ID_BUTTON_0, 12,  259, 55,  25,  0, 0x0,  0 },
  { BUTTON_CreateIndirect, Quit,          ID_BUTTON_1, 171, 259, 55,  25,  0, 0x0,  0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};


/*********************************************************************
*
*       _cbDialog
*/

static int ads_press_cnt = 0;

#if 0
WM_HWIN ADS_Get_Speed(void)
{
    return WM_GetDialogItem(g_hWin_AdvanSet,ID_EDIT_0);
}
#endif

WM_HWIN ADS_GetSrcOutTime(void)
{
    return WM_GetDialogItem(g_hWin_AdvanSet,ID_EDIT_0);
}

WM_HWIN ADS_GetStDnTime(void)
{
    return WM_GetDialogItem(g_hWin_AdvanSet,ID_EDIT_1);
}


//向上选择
void ADS_SelEdt_Up(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    if(ads_press_cnt == 0)
    {
        hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);
        WM_SetFocus(hItem);
        
        ads_press_cnt = 1;
    }
    else
    {
        ads_press_cnt--;
        hItem=WM_GetDialogItem(pMsg->hWin,(ID_EDIT_0+ads_press_cnt));
        WM_SetFocus(hItem);
    }


}
//向下选择
void ADS_SelEdt_Down(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    if(ads_press_cnt == 1)
    {
        hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
        WM_SetFocus(hItem);

        ads_press_cnt = 0;
    }
    else
    {
        ads_press_cnt++;
        hItem=WM_GetDialogItem(pMsg->hWin,(ID_EDIT_0+ads_press_cnt));
        WM_SetFocus(hItem);
    }

}

void ADS_Color_Change(void)
{
    WM_HWIN hItem;
    int i;
    for(i=0;i<2;i++)
    {
        hItem=WM_GetDialogItem(g_hWin_AdvanSet,ID_EDIT_0+i);
        if(WM_HasFocus(hItem)==1)
        {
            EDIT_SetBkColor(hItem,0,GUI_GREEN);
        }
        else if(WM_HasFocus(hItem)==0)
        {
            EDIT_SetBkColor(hItem,0,0xC0C0C0);
        }
    }
}

void ADS_SetFocus(void)
{
    WM_HWIN hItem;
    hItem =  WM_GetDialogItem(g_hWin_AdvanSet,(ID_EDIT_0 + ads_press_cnt));
    WM_SetFocus(hItem);
}

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int     key_num;
  u8      tmp[16];
  key_num=((WM_KEY_INFO *)(pMsg->Data.p))->Key;

   
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) 
  {
      case WM_INIT_DIALOG:
        //
        // Initialization of 'freq'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
        //sprintf(tmp, "%d", g_sys_ctrl.shutdownTimeout);
        EDIT_SetText(hItem, "30");
        WM_DisableWindow(hItem);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
        //sprintf(tmp, "%d", g_sys_ctrl.sleepTimeout);
        EDIT_SetText(hItem, "120");
        WM_DisableWindow(hItem);

        hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
        BUTTON_SetBkColor(hItem,0,GUI_GREEN);
        WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

        hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
        BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
        WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

       //PUB_InitFreq(pMsg,ID_EDIT_1);
        
        break;
      // USER START (Optionally insert additional message handling)
      // USER END
      case WM_KEY:
        Id = WM_GetId(pMsg->hWinSrc);
        if(((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt == 1)
        {
            switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
            {
                case GUI_KEY_GREEN:
                   //WM_DeleteWindow(g_hWin_AdvanSet);
                   //WM_SetFocus(g_hWin_para);
                   WM_DeleteWindow(g_hWin_AdvanSet);
                   g_hWin_AdvanSet = HBWIN_NULL;
                   WM_SetFocus(g_hWin_para);
                   ads_press_cnt = 0;
                    break;
                    
                case GUI_KEY_YELLOW:
                   WM_DeleteWindow(g_hWin_AdvanSet);
                   g_hWin_AdvanSet = HBWIN_NULL;
                   WM_SetFocus(g_hWin_para);
                   ads_press_cnt = 0;
                    break;
#if 0
                case GUI_KEY_TAB:
                        ADS_Color_Change();
                    break;
#endif
                case GUI_KEY_UP:
                    ADS_SelEdt_Up(pMsg);
                    ADS_Color_Change();
                    break;

                case GUI_KEY_DOWN:
                    ADS_SelEdt_Down(pMsg);
                    ADS_Color_Change();
                    break;
                case GUI_KEY_ENTER:
                    switch(Id)
                    {
#if 0
                        case ID_EDIT_0:
                           g_hWin_speed = CreateSpeed(g_hWin_AdvanSet);
                           break;
#endif
                        case ID_EDIT_1:
                            g_sys_ctrl.selectWidget=EDIT_SHUTDOWN_TIME;
                            g_hWin_Input=Create_Edit_Set(g_hWin_para);
                            WM_SetFocus(g_hWin_Input);
 
                            break;
                        case ID_EDIT_0:
                            g_sys_ctrl.selectWidget=EDIT_SCR_OUTTIME;
                            g_hWin_Input=Create_Edit_Set(g_hWin_para);
                            WM_SetFocus(g_hWin_Input);
                            break;
                    }
                    break;
            }
        }
        break;
      default:
        WM_DefaultProc(pMsg);
        break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAdvanceSet
*/
WM_HWIN CreateAdvanceSet(void);
WM_HWIN CreateAdvanceSet(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_para, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
