/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

#if 0
#define ID_WINDOW_0     (GUI_ID_USER + 0x81)

//#define ID_DROPDOWN_0   (GUI_ID_USER + 0x86)

#define ID_EDIT_0     (GUI_ID_USER + 0x86)
#define ID_EDIT_1     (GUI_ID_USER + 0x87)
#define ID_EDIT_2     (GUI_ID_USER + 0x88)
#define ID_EDIT_3     (GUI_ID_USER + 0x89)
#define ID_EDIT_4     (GUI_ID_USER + 0x8A)


#define ID_TEXT_0     (GUI_ID_USER + 0x8B)
#define ID_TEXT_1     (GUI_ID_USER + 0x8C)
#define ID_TEXT_2     (GUI_ID_USER + 0x8D)
#define ID_TEXT_3     (GUI_ID_USER + 0x8E)
#define ID_TEXT_4     (GUI_ID_USER + 0x8F)
#define ID_BUTTON_0     (GUI_ID_USER + 0x90)
#define ID_BUTTON_1     (GUI_ID_USER + 0x91)
#define ID_BUTTON_2     (GUI_ID_USER + 0x92)
#define ID_BUTTON_3     (GUI_ID_USER + 0x93)
#define ID_BUTTON_4     (GUI_ID_USER + 0x94)
#define ID_PROGBAR_0    (GUI_ID_USER + 0x95)
#endif


#define ID_WINDOW_0 (GUI_ID_USER + 0x07)
#define ID_BUTTON_0 (GUI_ID_USER + 0x08)
#define ID_BUTTON_1 (GUI_ID_USER + 0x09)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0C)
#define ID_TEXT_0 (GUI_ID_USER + 0x0D)
#define ID_TEXT_1 (GUI_ID_USER + 0x0E)
#define ID_TEXT_2 (GUI_ID_USER + 0x0F)
#define ID_TEXT_3 (GUI_ID_USER + 0x10)
#define ID_TEXT_4 (GUI_ID_USER + 0x11)
#define ID_EDIT_0 (GUI_ID_USER + 0x12)
#define ID_EDIT_1 (GUI_ID_USER + 0x13)
#define ID_EDIT_2 (GUI_ID_USER + 0x14)
#define ID_EDIT_3 (GUI_ID_USER + 0x15)
#define ID_EDIT_4 (GUI_ID_USER + 0x16)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x17)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "CommProtoTest", ID_WINDOW_0, 0, 0, 240, 295, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button",  ID_BUTTON_0, 6, 14, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button",  ID_BUTTON_1, 151, 14, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button",  ID_BUTTON_2, 6, 267, 55, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button",  ID_BUTTON_3, 80, 267, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button",  ID_BUTTON_4, 178, 266, 55, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "addr",    ID_TEXT_0, 8, 49, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "ctlcode", ID_TEXT_1, 7, 83, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "dataflag", ID_TEXT_2, 10, 122, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "length", ID_TEXT_3, 10, 156, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   "data", ID_TEXT_4, 10, 195, 110, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_0, 130, 48, 103, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_1, 130, 82, 103, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_2, 130, 118, 103, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_3, 130, 156, 103, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect,   "Edit", ID_EDIT_4, 130, 195, 103, 20, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 12, 236, 216, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};




#if 1

static char std_Edit1_Text[8]; //edit文本字符串
static int  std_Edit1_Value;

static char std_Edit3_Text[32]; //edit文本字符串
static int  std_Edit3_Value;

#endif

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
//通信规约调试
static const char CommStdTest[]="\xe9\x80\x9a\xe4\xbf\xa1\xe8\xa7\x84\xe7\xba\xa6\xe8\xb0\x83\xe8\xaf\x95";

//1-目标地址
static const char TarAddr[]="1-\xe7\x9b\xae\xe6\xa0\x87\xe5\x9c\xb0\xe5\x9d\x80:";

//2-控制字
static const char CtlCode[]="2-\xe6\x8e\xa7\xe5\x88\xb6\xe5\xad\x97:";

//3-长度
static const char Length[]="4-\xe9\x95\xbf\xe5\xba\xa6:";

//4-数据标识
static const char DataSign[]="3-\xe6\x95\xb0\xe6\x8d\xae\xe6\xa0\x87\xe8\xaf\x86:";

//5-数据域
static const char DataField[]="5-\xe6\x95\xb0\xe6\x8d\xae:";

//F1路由表
static const char RoutTab[]="F1\xe8\xb7\xaf\xe7\x94\xb1\xe8\xa1\xa8";

//F2数据标识
static const char DataSignBtn[]="F2\xe6\x95\xb0\xe6\x8d\xae\xe6\xa0\x87\xe8\xaf\x86";

//读设备地址
static const char GetAddr[]="\xe8\xaf\xbb\xe8\xae\xbe\xe5\xa4\x87\xe5\x9c\xb0\xe5\x9d\x80";

//读数据
static const char Readdata[]="\xe8\xaf\xbb\xe6\x95\xb0\xe6\x8d\xae";

//写数据
static const char WriteData[]="\xe5\x86\x99\xe6\x95\xb0\xe6\x8d\xae";

//读取产品芯片型号
static const char ReadChip[]="\xe8\xaf\xbb\xe5\x8f\x96\xe4\xba\xa7\xe5\x93\x81\xe8\x8a\xaf\xe7\x89\x87\xe5\x9e\x8b\xe5\x8f\xb7";

//#消息内容
static const char Msg[]="#\xe6\xb6\x88\xe6\x81\xaf\xe5\x86\x85\xe5\xae\xb9";

//发送
static const char Send[]="\xe5\x8f\x91\xe9\x80\x81";

//取消
static const char Cancel[]="\xe5\x8f\x96\xe6\xb6\x88";

/*********************************************************************
*
*       _aDialogCreate
*/
#if 0
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,   "CommStdTest", ID_WINDOW_0,   0,   0,   240, 295, 0, 0x0,  0 }, 
  { BUTTON_CreateIndirect,   RoutTab,       ID_BUTTON_3,   9,   9,   90,  28,  0, 0x0,  0 },//路由表
  { BUTTON_CreateIndirect,   DataSignBtn,   ID_BUTTON_2,   147, 9,   90,  28,  0, 0x0,  0 },//数据标识
  { EDIT_CreateIndirect,     "Edit",        ID_EDIT_0,     96,  51,  135, 20,  0, GUI_645_ADDR_LENGTH, 0 },//AAAA
  { EDIT_CreateIndirect,     "EDIT",        ID_EDIT_4,     96,  85, 135,  19,  0, 0x0,  0 },
  { EDIT_CreateIndirect,     "Edit",        ID_EDIT_2,     96,  119, 135, 20,  0, 0x64, 0 },//123
  { EDIT_CreateIndirect,     "Edit",        ID_EDIT_1,     96,  156, 135, 20,  0, 0x64, 0 },//456
  { EDIT_CreateIndirect,     "Edit",        ID_EDIT_3,     96,  193, 135, 20,  0, 0x20, 0 },//789
  { BUTTON_CreateIndirect,   Send,          ID_BUTTON_0,   8,   264, 55,  25,  0, 0x0,  0 },//发送
  { BUTTON_CreateIndirect,   Msg,           ID_BUTTON_4,   80,  264, 81,  25,  0, 0x0,  0 },
  { BUTTON_CreateIndirect,   Cancel,        ID_BUTTON_1,   180, 264, 55,  25,  0, 0x0,  0 },//取消  
  { TEXT_CreateIndirect,     TarAddr,       ID_TEXT_0,     9,   51,  80,  20,  0, 0x0,  0 },
  { TEXT_CreateIndirect,     CtlCode,       ID_TEXT_1,     9,   85,  68,  20,  0, 0x0,  0 },
  { TEXT_CreateIndirect,     Length,        ID_TEXT_2,     9,   156, 80,  20,  0, 0x0,  0 },
  { TEXT_CreateIndirect,     DataSign,      ID_TEXT_3,     9,   119, 80,  20,  0, 0x0,  0 },
  { TEXT_CreateIndirect,     DataField,     ID_TEXT_4,     9,   195, 57,  20,  0, 0x0,  0 },
  { PROGBAR_CreateIndirect,  "Progbar",     ID_PROGBAR_0,  9,   228, 222, 20,  0, 0x0,  0 },
      // USER START (Optionally insert additional widgets)
      // USER END
    };
#endif

u8 GUI_char2hex(u8 ch);

u8 GUI_char2hex(u8 ch)
{
    if((ch >= '0') && (ch <= '9'))
    {
        return (ch-'0');
    }
    if((ch >= 'a') && (ch <= 'f'))
    {
        return ((ch-'a')+10);
    }
    if((ch >= 'A') && (ch <= 'F'))
    {
        return ((ch-'A')+10);
    }
    return 0xff;
}
/**************************************************************
                    从控件上获取参数

***************************************************************/


const u8 c_645ctrlDef[2][PLC_CTRL_MAX_NUM] = 
{ 
    //97规约
    {0x05, 0x01, 0x04,  4,5,6,7,8,9,10,11,12,13,14,15,16},
    //07规约
    {0x13, 0X11, 0X14,  4,5,6,7,8,9,10,11,12,13,14,15,16}
};

void CST_Set_DataFlag(u8 * tst)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_std,(ID_EDIT_2));
    EDIT_SetText(hItem, tst); 
}


void STM_Print_resp_data(u8 * src, u8 * send_ptr, u8 len)
{
    u8 i;
    for(i = 0; i < len; i++)
    {
        *send_ptr++ = GUI_Hex2Char( src[i]>>4);
        *send_ptr++ = GUI_Hex2Char( src[i]&0x0f);
        *send_ptr++ = ' ';
    }
    *send_ptr++ = 0;
}


void STM_proc_resp_data(void)
{
    WM_HWIN hItem;
    u8 * pbuf, temb[32];
    u32 len;

    pbuf = g_plc_prm.data_buf;
    len = g_plc_prm.data_len;

    if(g_hWin_std != WM_HWIN_NULL)
    {        
        hItem = WM_GetDialogItem(g_hWin_std, ID_EDIT_1);
        sprintf(temb, "%d", len);
        EDIT_SetText(hItem, temb);
        
        //SWITCH(DATA FLAG)
        if(len)
        {
            if(len > 8)
                len = 8;
            hItem = WM_GetDialogItem(g_hWin_std, ID_EDIT_3);
            STM_Print_resp_data(pbuf,temb, len);      
            EDIT_SetText(hItem, temb);           
        }                            
    }
}


static u32 Get_Para_From_Widget(WM_MESSAGE * pMsg)
{
    u8  i, tb[GUI_645_ADDR_LENGTH+2], len;
    WM_HWIN hItem;
    WM_HWIN hWin;
 
    int dropdown_num;
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
    EDIT_GetText(hItem, tb, GUI_645_ADDR_LENGTH+1);

    if(strlen(tb) != GUI_645_ADDR_LENGTH)
    {
        ERR_NOTE(g_hWin_std,GUI_MSBOX_ADDR_ERROR);
        //g_hWin_Err=CreateErrNote(g_hWin_std);
        //hItem=ERR_Get_Text();
        //TEXT_SetText(hItem,"NONONO");
        return DEV_ERROR;
    }
    
    if(DEV_OK != GUI_GetMeterAddr(tb))
    {
        ERR_NOTE(g_hWin_std,GUI_MSBOX_ADDR_ERROR);
        return DEV_ERROR;
    }    
    //

    //control word
    hItem=WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_0);
    dropdown_num=DROPDOWN_GetSel(hItem);

    if(dropdown_num >= PLC_CTRL_MAX_NUM)
        dropdown_num  = PLC_CTRL_MAX_NUM - 1;

    if(g_sys_register_para.plcProtocol == DL_T_07)
    {
        g_send_para_pkg.ctlCode = c_645ctrlDef[g_sys_register_para.plcProtocol][dropdown_num]; 
    }
    else if(g_sys_register_para.plcProtocol == DL_T_97)
    {
        g_send_para_pkg.ctlCode = c_645ctrlDef[g_sys_register_para.plcProtocol][dropdown_num]; 
    }
    else
    {        
        ERR_NOTE(g_hWin_std,GUI_MSBOX_PROC_ERROR); 
        
        //g_hWin_Err=CreateErrNote(g_hWin_std);
        return DEV_ERROR;
    }
        //g_sys_register_para.plcProtocol = DL_T_07;

  
    hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_2);
    //g_send_para_pkg.g_datasign = EDIT_GetValue(pMsg->hWin);
    EDIT_GetText(hItem, tb, 8 + 1);

    if(g_sys_register_para.plcProtocol == DL_T_07)
        len = DL645_07_DATA_ITEM_LEN;
    else
        len = DL645_97_DATA_ITEM_LEN;
    
    if(strlen(tb) != (len<<1))
    {       
        ERR_NOTE(g_hWin_std,GUI_MSBOX_DIDO_ERROR);
        
        //g_hWin_Err=CreateErrNote(g_hWin_std);
        return DEV_ERROR;
    }

    if(DEV_OK != GUI_GetStrDataFlag(tb, g_sys_register_para.plcProtocol ))
    {
        ERR_NOTE(g_hWin_std,GUI_MSBOX_DIDO_ERROR);
        
        //g_hWin_Err=CreateErrNote(g_hWin_std);
        
        
        
        return DEV_ERROR;
    }
    

    hItem = WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);/*长度*/
    EDIT_GetText(hItem,std_Edit1_Text,4);
    g_send_para_pkg.dataLen = atoi(std_Edit1_Text);
  
    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_3);/*数据*/
    EDIT_GetText(hItem, tb, 20);

    g_send_para_pkg.cmdType = PLC_CMD_TYPE_COMMON;

    return DEV_OK;

    


}



/**************************************************************
*
*                初始化对话框
*
***************************************************************/
static void _init_dialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    u8 tempbuf[10];
    int i;  

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
    BUTTON_SetBkColor(hItem,0,GUI_GREEN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
    BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
    BUTTON_SetBkColor(hItem,0,GUI_CYAN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    
    //hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2); 
    //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    Not_Focus(pMsg,ID_BUTTON_2);

    //hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3); 
    //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    Not_Focus(pMsg,ID_BUTTON_3);

    //hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4); 
    //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    //Not_Focus(pMsg,ID_BUTTON_4);

    //
    // Initialization of 'Edit'
    //
    for(i=0;i<5;i++)
    {
        hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0+i);
        WM_DisableWindow(hItem);
    }
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);    
    EDIT_SetText(hItem, GUI_hex2MeterAddrStr(g_sys_control.recentMeterAddr, 6));
    //
    // Initialization of 'Dropdown'
    //
#if 0
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, GetAddr);
    DROPDOWN_AddString(hItem, Readdata);
    DROPDOWN_AddString(hItem, WriteData);
    DROPDOWN_AddString(hItem, ReadChip);

    DROPDOWN_SetSel(hItem, 1);
    //
    // Initialization of 'Ed1it'
    //
#endif 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "0");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    GUI_GetHexDataFlag(tempbuf, g_sys_control.defaultDataFlag, 4);
    EDIT_SetText(hItem, tempbuf);
    
    
    //EDIT_SetText(hItem, "0");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "00 00 00 00");

    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetBarColor(hItem,0,GUI_GREEN);
}

WM_HWIN STM_Get_PROGBAR()
{    
     return WM_GetDialogItem(g_hWin_std, ID_PROGBAR_0);            
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int TimeCount;//进度条计时

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    GUI_UC_SetEncodeUTF8();
    _init_dialog(pMsg);
    
    break;
#if 0
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) 
    {
        case ID_DROPDOWN_0:
            Disable_Widget(pMsg,ID_EDIT_0);
            Disable_Widget(pMsg,ID_EDIT_1);
            Disable_Widget(pMsg,ID_EDIT_2);
            Disable_Widget(pMsg,ID_EDIT_3);
            break;
        case ID_EDIT_0:
            Enable_Widget(pMsg,ID_EDIT_0);
            Disable_Widget(pMsg,ID_EDIT_1);
            Disable_Widget(pMsg,ID_EDIT_2);
            Disable_Widget(pMsg,ID_EDIT_3);
            break;
        case ID_EDIT_1:
            Disable_Widget(pMsg,ID_EDIT_0);
            Enable_Widget(pMsg,ID_EDIT_1);
            Disable_Widget(pMsg,ID_EDIT_2);
            Disable_Widget(pMsg,ID_EDIT_3);
            break;
        case ID_EDIT_2:
            Disable_Widget(pMsg,ID_EDIT_0);
            Disable_Widget(pMsg,ID_EDIT_1);
            Enable_Widget(pMsg,ID_EDIT_2);
            Disable_Widget(pMsg,ID_EDIT_3);
            break;
        case ID_EDIT_3:
            Disable_Widget(pMsg,ID_EDIT_0);
            Disable_Widget(pMsg,ID_EDIT_1);
            Disable_Widget(pMsg,ID_EDIT_2);
            Enable_Widget(pMsg,ID_EDIT_3);
            break;
    }
        
  break;
#endif

  //拦截消息
    case WM_KEY:
        
       Id    = WM_GetId(pMsg->hWinSrc);
#if 0       
       if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==1)
       {
           if((Id >=  ID_EDIT_0) && (Id <=  ID_EDIT_3))
           {
                if((((WM_KEY_INFO*)(pMsg->Data.p))->Key) == GUI_KEY_ESCAPE)
                {
                    Disable_Widget(pMsg,ID_EDIT_0);
                    Disable_Widget(pMsg,ID_EDIT_1);
                    Disable_Widget(pMsg,ID_EDIT_2);
                    Disable_Widget(pMsg,ID_EDIT_3);
                    hItem=WM_GetDialogItem(g_hWin_std,ID_DROPDOWN_0);
                    WM_SetFocus(hItem);
                }
                else if((((WM_KEY_INFO*)(pMsg->Data.p))->Key) == GUI_KEY_YELLOW)
                {
                    WM_DeleteWindow(g_hWin_std);
                    g_hWin_std=HBWIN_NULL;
                    WM_SetFocus(g_hWin_menu);
                    break;
                }
                else 
                {
                    break;
                }
            }
       }
#endif            
            switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
            {
#if 0
                case '1':
                    Focus_Widget(pMsg,ID_EDIT_0);
                    break;
                case '2':
                    Focus_Widget(pMsg,ID_DROPDOWN_0);  
                    break;
                case '3':
                    Focus_Widget(pMsg,ID_EDIT_2);  
                    break;    
                case '4':
                    Focus_Widget(pMsg,ID_EDIT_1);  
                    break;
                case '5':
                    Focus_Widget(pMsg,ID_EDIT_3);  
                    break;
#endif
                case GUI_KEY_YELLOW:
                    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==1)
                    {
                        WM_DeleteWindow(g_hWin_std);
                        g_hWin_std = HBWIN_NULL;
                        WM_BringToBottom(g_hWin_msg);
                        WM_HideWindow(g_hWin_msg);
                        WM_ShowWindow(g_hWin_TimeBar);
                        WM_ShowWindow(g_hWin_Date);
                        WM_SetFocus(g_hWin_menu); 
                    }
                    break;

                case GUI_KEY_F1:
                    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
                    {
                        g_hWin_relay=CreateRelayAddr();
                        WM_ShowWindow(g_hWin_relay);
                        WM_SetFocus(g_hWin_relay);
                    }
                    break;
                case GUI_KEY_F2:
                    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
                    {
                        g_hWin_DataSign=CreateDataSign();
                        WM_ShowWindow(g_hWin_DataSign);
                        WM_SetFocus(g_hWin_DataSign);
                    }
                    break;
                case '#':
                    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
                    {
                        WM_BringToTop(g_hWin_msg);
                        WM_ShowWindow(g_hWin_msg);                    
                        WM_SetFocus(g_hWin_msg);
                    }
                    break;
                case GUI_KEY_GREEN:
                    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
                    {
                        if(DEV_OK == Get_Para_From_Widget(pMsg))//获取参数数据
                        {
                            g_sys_control.guiState = GUI_PLC_MSG_TEST;
                            OSMboxPost(g_sys_control.downMb,(void*)&g_send_para_pkg);
                        }     
                    }
                    break;
            } 
       
        break;



    
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}


/*********************************************************************
*
*       CreateCommStdTest
*/
WM_HWIN CreateCommStdTest(void);
WM_HWIN CreateCommStdTest(void) {
  WM_HWIN hWin;
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  
  return hWin;
}


/*************************** End of file ****************************/

