/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)
#define ID_TEXT_3    (GUI_ID_USER + 0x04)
#define ID_EDIT_0    (GUI_ID_USER + 0x05)
#define ID_EDIT_1    (GUI_ID_USER + 0x06)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x07)
#define ID_BUTTON_0  (GUI_ID_USER + 0x08)
#define ID_BUTTON_1  (GUI_ID_USER + 0x09)
#define ID_BUTTON_2  (GUI_ID_USER + 0x0A)
#define ID_PROGBAR_1 (GUI_ID_USER + 0x0B)
#define ID_TEXT_4    (GUI_ID_USER + 0x0C)



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char MemSize[]="\xe5\xae\xb9\xe9\x87\x8f";
static const char MemUsage[]="\xe4\xbd\xbf\xe7\x94\xa8\xe7\x8e\x87";
static const char FileNum[]="\xe6\x96\x87\xe4\xbb\xb6\xe6\x95\xb0\xe7\x9b\xae";
static const char FactorySet[]="\xe6\x81\xa2\xe5\xa4\x8d\xe5\x87\xba\xe5\x8e\x82\xe8\xae\xbe\xe7\xbd\xae";
static const char MemFormat[]="\xe6\xa0\xbc\xe5\xbc\x8f\xe5\x8c\x96";
static const char MemReturn[]="\xe8\xbf\x94\xe5\x9b\x9e";
static const char MemConfirm[]="F1\xe7\xa1\xae\xe5\xae\x9a";
static const char VersionNum[]="\xe7\x89\x88\xe6\x9c\xac\xe5\x8f\xb7:20150127";
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,   "MemManage",  ID_WINDOW_0,  0,   0,   240, 295,0, 0x0,  0 },
  { TEXT_CreateIndirect,     MemSize,      ID_TEXT_0,    15,  22,  80,  20, 0, 0x0,  0 },
  { TEXT_CreateIndirect,     MemUsage,     ID_TEXT_1,    15,  111, 80,  20, 0, 0x0,  0 },
  { TEXT_CreateIndirect,     FileNum,      ID_TEXT_2,    15,  65,  80,  20, 0, 0x0,  0 },
  { TEXT_CreateIndirect,     FactorySet,   ID_TEXT_3,    15,  155, 108, 20, 0, 0x0,  0 },
  { TEXT_CreateIndirect,     VersionNum,    ID_TEXT_4,    15,  185, 200, 20, 0, 0x0,  0 },
  { EDIT_CreateIndirect,     "Edit",       ID_EDIT_0,    120, 21,  110, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect,     "Edit",       ID_EDIT_1,    120, 67,  110, 20, 0, 0x64, 0 },
  { PROGBAR_CreateIndirect,  "Progbar",    ID_PROGBAR_0, 120, 113, 110, 20, 0, 0x0,  0 },
  { BUTTON_CreateIndirect,   MemConfirm,   ID_BUTTON_0,  120, 152, 110, 25, 0, 0x0,  0 },
  { BUTTON_CreateIndirect,   MemFormat,    ID_BUTTON_1,  11,  260, 80,  25, 0, 0x0,  0 },
  { BUTTON_CreateIndirect,   MemReturn,    ID_BUTTON_2,  149, 260, 80,  25, 0, 0x0,  0 },
  { PROGBAR_CreateIndirect,  "Progbar",    ID_PROGBAR_1, 9,   228, 222, 20,  0, 0x0,  0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

WM_HWIN MMD_Get_PROGBAR()
{    
     return WM_GetDialogItem(g_hWin_mem, ID_PROGBAR_0);            
}

void MMD_Set_FD_PROGBAR(u32 newVal)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_mem, ID_PROGBAR_1);  
    if(hItem != WM_HWIN_NULL)
    {
        //g_sys_control.testProgBarVal = 100;
        PROGBAR_SetValue(hItem, newVal);              
    }
}

void MMD_Format_Disk(void)
{
    
    FRESULT res;
    FATFS fs;

    res = f_mount(SD_DRV, &fs);

    if(FR_OK == res)
    {
        res = f_mkfs(SD_DRV, SD_FORMAT, _MAX_SS);

        if(FR_OK == res)
        {
            //DEBUG_PRINT(("SD format ok!\n"));
            MMD_Set_FD_PROGBAR(100);
            
        }                        
    }
    f_mount(SD_DRV, NULL);
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
      WM_HWIN hItem;
      int     NCode;
      int     Id;
      u8    sbuf[64];

      switch (pMsg->MsgId) 
      {
          case WM_INIT_DIALOG:
            get_sd_info();
            
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
            sprintf(sbuf, "%dMB", (g_sys_control.sd_total_capacity/1024));
            EDIT_SetText(hItem, sbuf);
            
            //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
            WM_DisableWindow(hItem);
            
            hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
            EDIT_SetText(hItem, "1");
            //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
            WM_DisableWindow(hItem);

            hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
            NCode = (100*g_sys_control.sd_free_capacity)/g_sys_control.sd_total_capacity;
            NCode %= 100;
            NCode = 100-NCode;
            PROGBAR_SetValue(hItem, NCode);
            //sprintf(sbuf, "%dMbytes", (g_sys_control.sd_total_capacity/1024));
            
            hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
            BUTTON_SetBkColor(hItem,0,GUI_GREEN);
            WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
            
            hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
            BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
            WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

            hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
            BUTTON_SetBkColor(hItem,0,GUI_CYAN);
            WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

            //hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_1);     
            //PROGBAR_SetValue(hItem, 100);

            
            
            break;
          case WM_NOTIFY_PARENT:
            Id    = WM_GetId(pMsg->hWinSrc);
            NCode = pMsg->Data.v;
            switch(Id) {}
            break;
          case WM_KEY:
            
            if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
            {
                switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
                {
                    case GUI_KEY_GREEN:
                        //SYS_ADD_TASK(SYS_TASK_FORMAT_DISK);
                        ERR_NOTE(g_hWin_mem, 4);//»∑»œ∏Ò ΩªØÂ
                        break;
                    case GUI_KEY_YELLOW:
                        WM_DeleteWindow(g_hWin_mem);
                        g_hWin_mem=0;
                        WM_ShowWindow(g_hWin_TimeBar);
                        WM_ShowWindow(g_hWin_Date);
                        WM_SetFocus(g_hWin_menu);
                        break;
                    case GUI_KEY_F1:
                        break;
                }
            }   
                
            break;
          default:
            WM_DefaultProc(pMsg);
            break;
      }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMemManage
*/
WM_HWIN CreateMemManage(void);
WM_HWIN CreateMemManage(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
