/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/


#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

#define ID_WINDOW_0     (GUI_ID_USER + 0x89)

#define ID_BUTTON_0     (GUI_ID_USER + 0x8B)
#define ID_BUTTON_1     (GUI_ID_USER + 0x8C)
#define ID_BUTTON_2     (GUI_ID_USER + 0x8D)
#define ID_BUTTON_3     (GUI_ID_USER + 0x8E)
#define ID_BUTTON_4     (GUI_ID_USER + 0x8F)
#define ID_BUTTON_5     (GUI_ID_USER + 0x90)

#define ID_TEXT_0       (GUI_ID_USER + 0x91)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x92)


// USER START (Optionally insert additional defines)
//static int PressCount = 0;  //对按键次数计数

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

//设置命令选择
static const char CmdSel[]="\xe8\xae\xbe\xe7\xbd\xae\xe9\x80\x89\xe6\x8b\xa9";

//发送数据
//static const char SendData[]="\xe5\x8f\x91\xe9\x80\x81\xe6\x95\xb0\xe6\x8d\xae";
static const char Data[]="\xe6\x95\xb0\xe6\x8d\xae";


//接收数据
static const char RevData[]="\xe6\x8e\xa5\xe6\x94\xb6\xe6\x95\xb0\xe6\x8d\xae";

//设为监控器状态 
static const char Monitor[]="\xe8\xae\xbe\xe4\xb8\xba\xe7\x9b\x91\xe6\x8e\xa7\xe5\x99\xa8\xe7\x8a\xb6\xe6\x80\x81";

//设为抄控器状态
static const char Copy[]="\xe8\xae\xbe\xe4\xb8\xba\xe6\x8a\x84\xe6\x8e\xa7\xe5\x99\xa8\xe7\x8a\xb6\xe6\x80\x81";

//读取模块状态
static const char ReadModule[]="\xe8\xaf\xbb\xe5\x8f\x96\xe6\xa8\xa1\xe5\x9d\x97\xe7\x8a\xb6\xe6\x80\x81";

//读载波节点
static const char ReadNope[]="#\xe8\xaf\xbb\xe8\xbd\xbd\xe6\xb3\xa2\xe8\x8a\x82\xe7\x82\xb9";

//设置
static const char Sel[]="#\xe8\xae\xbe\xe7\xbd\xae";


//停止
static const char Stop[]="F2 \xe5\x81\x9c \xe6\xad\xa2";

//清除
static const char ClearScr[]="* \xe6\xb8\x85 \xe9\x99\xa4";

//取消
static const char Cancel[]="\xe5\x8f\x96\xe6\xb6\x88";

//开始
static const char Start[]="F1 \xe5\xbc\x80 \xe5\xa7\x8b";

//保存
static const char Save[]="\xe4\xbf\x9d\xe5\xad\x98";
/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, NULL, ID_WINDOW_0, 0, 0, 240, 295, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ReadNope, ID_BUTTON_0, 142, 43, 93, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, ClearScr, ID_BUTTON_1, 8, 43, 90, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Start, ID_BUTTON_2, 8, 8, 90, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Cancel, ID_BUTTON_3, 182, 265, 55, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Save, ID_BUTTON_4, 10, 265, 55, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Data, ID_TEXT_0, 10, 73, 56, 20, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, NULL, ID_MULTIEDIT_0, 4, 93, 232, 163, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Stop, ID_BUTTON_5, 142, 10, 93, 25, 0, 0x0, 0 },
};



/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

 
/**************************************************************
*
*                     初始化对话框
*
***************************************************************/
static void _init_dialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
    BUTTON_SetBkColor(hItem,0,GUI_GREEN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
     
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
    BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_5);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    

    
   // hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
   // DROPDOWN_AddString(hItem, Monitor);
    //DROPDOWN_AddString(hItem, Copy);
    //DROPDOWN_AddString(hItem, ReadNope);
    //
    // Initialization of 'Multiedit'
    //
    //hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    //MULTIEDIT_SetText(hItem, "Multiedit");
    
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    MULTIEDIT_SetAutoScrollV(hItem,1);
    MULTIEDIT_SetReadOnly(hItem,1);




}

WM_HWIN MND_Get_MultiEdit()
{
    return WM_GetDialogItem(g_hWin_monitor,ID_MULTIEDIT_0);
}


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Dropdown'
    //
    GUI_UC_SetEncodeUTF8();
    _init_dialog(pMsg);

    
   // WM_DisableWindow(hItem);//还要对上下左右键盘有反应，所以不能disable
   
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) 
    {
        default:break;
    }
    break;
  case WM_KEY:
    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)//按键释放。added on 2015.1.4
    {
        switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
        {
            case GUI_KEY_YELLOW:
                WM_DeleteWindow(g_hWin_monitor);
                g_hWin_monitor=HBWIN_NULL;
                WM_ShowWindow(g_hWin_TimeBar);
                WM_ShowWindow(g_hWin_Date);
                WM_SetFocus(g_hWin_menu);
                break;
            case '#':
                ButtonBlink(pMsg,ID_BUTTON_0);
                break;
            case '*':
                ButtonBlink(pMsg,ID_BUTTON_1);
                break;
            case GUI_KEY_F1:
                ButtonBlink(pMsg,ID_BUTTON_2);
                //TSK_Set_Monitor();
                g_send_para_pkg.cmdType = PLC_CMD_TYPE_R2L;
                g_sys_control.guiState = GUI_PLC_MSG_LISTING;                        
                OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                break;
            case GUI_KEY_F2:
                ButtonBlink(pMsg,ID_BUTTON_5);
                //TSK_Close_Monitor();
                g_send_para_pkg.cmdType = PLC_CMD_TYPE_L2R;
                g_sys_control.guiState = GUI_PLC_MSG_LISTING;
                OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                break;
        }
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  case WM_MSG_CLOSE:
    WM_DeleteWindow(g_hWin_monitor);
	break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMonitor
*/
WM_HWIN CreateMonitor(void);
WM_HWIN CreateMonitor(void) {
  WM_HWIN hWin;
  //WM_HWIN hItem;
  //GUI_COLOR color=0x000000;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  return hWin;
}







