/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "includes.h"

//#define PAGE_SWITCH (WM_USER+0)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

//任务栏资源ID　
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_TEXT_3     (GUI_ID_USER + 0x04)
#define ID_TEXT_4     (GUI_ID_USER + 0x05)

#define ID_TEXT_5     (GUI_ID_USER + 0x06)
#define ID_TEXT_6     (GUI_ID_USER + 0x07)
#define ID_TEXT_7     (GUI_ID_USER + 0x08) 
#define ID_TEXT_8     (GUI_ID_USER + 0x09) 
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x0A) 
#define ID_TEXT_9     (GUI_ID_USER + 0x0B) 
//#define ID_TEXT_10    (GUI_ID_USER + 0x0C) 


extern GUI_CONST_STORAGE GUI_BITMAP _bmSystem;
extern GUI_CONST_STORAGE GUI_BITMAP _bmRead;
extern GUI_CONST_STORAGE GUI_BITMAP _bmRemote;
extern GUI_CONST_STORAGE GUI_BITMAP _bmWriteRad;
extern GUI_CONST_STORAGE GUI_BITMAP _bmEmailRad;
extern GUI_CONST_STORAGE GUI_BITMAP _bmmonitor;
extern GUI_CONST_STORAGE GUI_BITMAP bmmeter;
extern GUI_CONST_STORAGE GUI_BITMAP bmwave;
extern GUI_CONST_STORAGE GUI_BITMAP bmprotocal;
extern GUI_CONST_STORAGE GUI_BITMAP bmabout;
extern GUI_CONST_STORAGE GUI_BITMAP bmTFcard; 



//icon信息结构体
typedef struct {
  const GUI_BITMAP * pBitmap;
  const char       * pText;
} BITMAP_ITEM;


//通信参数设置
static const char CommParaSetText[]="\xe5\x8f\x82\xe6\x95\xb0\xe8\xae\xbe\xe7\xbd\xae";

//通信规约调试
static const char CommStdTestText[]="\xe8\xa7\x84\xe7\xba\xa6\xe8\xb0\x83\xe8\xaf\x95";

//载波功能设置
static const char WaveCarrierText[]="\xe8\xbd\xbd\xe6\xb3\xa2\xe8\xae\xbe\xe7\xbd\xae";

//内存管理
static const char TFcardText[]="\xe5\x86\x85\xe5\xad\x98\xe7\xae\xa1\xe7\x90\x86";



//智能抄表
static const char ReadMeterText[]="\xe6\x99\xba\xe8\x83\xbd\xe6\x8a\x84\xe8\xa1\xa8";

//状态监控
static const char MonitorText[]="\xe7\x8a\xb6\xe6\x80\x81\xe7\x9b\x91\xe6\x8e\xa7";

//帮助说明
static const char About[]="\xe8\xaf\xb4\xe6\x98\x8e\xe5\xb8\xae\xe5\x8a\xa9";

//上行标志

static const char UploadIcon[]="\xe5\xa3\xb9";

//\xe8\xb4\xb0

//下行标志
static const char DownloadIcon[]="\xe8\xb4\xb0";

//电池
static const char Battery_100[]="\xe5\x8d\x81";
static const char Battery_80[] ="\xe7\x8e\x96";
static const char Battery_60[] ="\xe6\x8d\x8c";
static const char Battery_40[] ="\xe6\x9f\x92";
static const char Battery_20[] ="\xe9\x99\x86";

//监控
static const char MonitorIcon[]="\xe8\x82\x86";
//关闭监控
static const char CloseMonitor[]="\xe5\x8f\x81";

//当前规约:DL-T-07
static const char Protocol_07[]="\xe8\xa7\x84\xe7\xba\xa6:DL-T-07";

static const char Protocol_97[]="\xe8\xa7\x84\xe7\xba\xa6:DL-T-97";



//任务栏资源列表
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,  NULL,           ID_WINDOW_0,  0,   0, 240, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect,    "protocol",     ID_TEXT_0,    3,   3, 100,  15, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect,    MonitorIcon ,   ID_TEXT_1,    78,  5, 40,  15, 0, 0x0, 0 },
  { TEXT_CreateIndirect,    UploadIcon,     ID_TEXT_5,    143, 5, 17,  17, 0, 0x0, 0 }, 
  { TEXT_CreateIndirect,    DownloadIcon,   ID_TEXT_6,    160, 5, 17,  17, 0, 0x0, 0 },
  { TEXT_CreateIndirect,    " ",            ID_TEXT_7,    190, 4, 42,  17, 0, 0x0, 0 },
    
};



static const BITMAP_ITEM _aBitmapItem[] = 
{
  
  {&_bmSystem,    CommParaSetText  },  //通信参数设置
  {&bmmeter,      ReadMeterText    },  //常用抄表 
  {&bmprotocal,   CommStdTestText  },  //通信规约调试
  {&_bmmonitor,   MonitorText      },  //监控
  {&bmTFcard,     TFcardText       },  //内存管理 
  {&bmabout,      About            }
  	
};


WM_HWIN TSK_Get_Upload_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_5);
}

WM_HWIN TSK_Get_Download_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_6);
}

WM_HWIN TSK_Get_Protocol_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
}

void TSK_Set_Monitor(void)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_1);
    TEXT_SetFont(hItem,&GUI_Font_Battery_40);
    TEXT_SetText(hItem,MonitorIcon);
}

void TSK_Set_Protocol_Text(void)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
    if(g_sys_register_para.plcProtocol==DL_T_07)
    {
        TEXT_SetText(hItem,Protocol_07);
    }
    else if(g_sys_register_para.plcProtocol==DL_T_97)
    {
        TEXT_SetText(hItem,Protocol_97);
    }
}

#if 0
void TSK_Close_Monitor(void)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_1);
    TEXT_SetFont(hItem,&GUI_Font_Battery_40);
    TEXT_SetText(hItem,CloseMonitor);
}
#endif


/************************************************
数据上行
************************************************/
void Data_Upload_Green(u32 color)
{
    WM_HWIN hItem;
    static u32 i = 0;
    /*数据发送*/
    
    if(color)
    {
        i = ICON_FLOW_FLASH_TIMEOUT;
        hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_5);
        TEXT_SetTextColor(hItem, GUI_GREEN );//GUI_GREEN);
    }
    else
    {
        if(i == 0xffffffff)
        {
            //i--;
        }
        else if(i)
        {
            i--;
        }
        else
        {
            hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_5);
            TEXT_SetTextColor(hItem, GUI_WHITE );//GUI_GREEN);
            i = 0xffffffff;
        }
    }
        
    //GUI_Delay(15);
    //TEXT_SetTextColor(hItem,GUI_WHITE);
}


/************************************************
数据下行
************************************************/

void Data_Download_Yellow(u32 color)
{
    WM_HWIN hItem;
    static u32 i;
    
    if(color)
    {
        i = ICON_FLOW_FLASH_TIMEOUT;
        hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_6);
        TEXT_SetTextColor(hItem, GUI_YELLOW);  //GUI_YELLOW);
    }
    else
    {
        if(i == 0xffffffff)
        {
            //i--;
            
        }
        else if(i)
        {
            i--;
        }
        else
        {
            hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_6);
            TEXT_SetTextColor(hItem, GUI_WHITE );//GUI_GREEN);
            i = 0xffffffff;
        }               
    }
}


void Battery_State(uint16_t pwr_val)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_7);
    if((pwr_val>2079)&&(pwr_val<2172))
    {
        TEXT_SetText(hItem,Battery_20);
        TEXT_SetTextColor(hItem,GUI_RED);
    }
    else if((pwr_val>=2175)&&(pwr_val<2230))
    {
        TEXT_SetText(hItem,Battery_40);
        TEXT_SetTextColor(hItem,GUI_YELLOW);
    }
    else if((pwr_val>=2236)&&(pwr_val<2262))
    {
        TEXT_SetText(hItem,Battery_60);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }
    else if((pwr_val>=2265)&&(pwr_val<2291))
    {
        TEXT_SetText(hItem,Battery_80);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }
    else if(pwr_val>=2298)
    {
        TEXT_SetText(hItem,Battery_100);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }



}

//任务栏回调函数

static void _cbTaskDialog(WM_MESSAGE * pMsg) 
{

  WM_HWIN hItem;
  int widget_id;
  
  switch (pMsg->MsgId) 
  {
      case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        WINDOW_SetBkColor(pMsg->hWin, GUI_GRAY);
        
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_5);
        TEXT_SetTextColor(hItem,GUI_WHITE);
        
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_6);
        TEXT_SetTextColor(hItem,GUI_WHITE);
#if 0
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_1);
        TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        TEXT_SetText(hItem,MonitorIcon);
        TEXT_SetTextColor(hItem,GUI_RED);
#endif


#if 1
        //TSK_Set_Protocol_Text();
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_0);

        if(g_sys_register_para.plcProtocol==DL_T_07)
        {
            TEXT_SetText(hItem,Protocol_07);
        }
        else if(g_sys_register_para.plcProtocol==DL_T_97)
        {
            TEXT_SetText(hItem,Protocol_97);
        }
#endif       
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_7); 
        TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        break;
      case WM_TIMER:
        Battery_State(g_sys_control.pwrValue);
        WM_RestartTimer(pMsg->Data.v, 1000);
        break;

      default:
        WM_DefaultProc(pMsg);
        break;
  }
}


/*********************************************************************
*
*       _cbDialog
*/

static void _cbIconWin(WM_MESSAGE * pMsg) 
{
	int     NCode;
	int     Id;
	int IconViewIndex;//索引
	WM_HWIN hIconView;
	hIconView = g_hWin_menu;
	IconViewIndex=ICONVIEW_GetSel(hIconView);
	switch (pMsg->MsgId) 
	{   

        case WM_INIT_DIALOG:
            break;
		case WM_PAINT: 
			GUI_SetBkColor(0xb2c7ca);
			GUI_Clear();
			break;
		case WM_KEY:
            
           // if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
            {
            
			switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
			{
				case GUI_KEY_ENTER:
					switch(IconViewIndex)
					{	
						case 0:
							g_hWin_para = CreateCommParaSet();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_para);
							break;
                            
						case 2:
							g_hWin_std = CreateCommStdTest();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_std);
							break;
						case 4:
							g_hWin_mem=CreateMemManage();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_mem);
							break;
                            
                        case 1:
			                g_hWin_ReadMeter=CreateReadMeter();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_ReadMeter);
							break;
                            
						case 3:
							g_hWin_monitor=CreateMonitor();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_monitor);
							break;
                            
                        case 5:
                            g_hWin_about=Createabout();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_about);
                            break;
						
						default:
							break;
					}
				break;
			}
            }
			break;
		default:
			WM_DefaultProc(pMsg);
			break;
	}
}


/*********************************************************************
*
*       Public code
*
**********************************************************************
*/


WM_HWIN TimeBarDisp(void)
{
    WM_HWIN hText;
    hText=TEXT_CreateEx(20,30,200,31,g_hWin_menu,WM_CF_SHOW,TEXT_CF_HCENTER,ID_TEXT_8,"00:00");
    TEXT_SetFont(hText,&GUI_Fontcn27);
    TEXT_SetTextColor(hText,GUI_DARKGRAY);
    return hText;
}


WM_HWIN DateBarDisp(void)
{
    WM_HWIN hText;
    hText=TEXT_CreateEx(20,63,200,21,g_hWin_menu,WM_CF_SHOW,TEXT_CF_HCENTER,ID_TEXT_9," ");
    TEXT_SetFont(hText,&GUI_Fontdate20);
    //TEXT_SetTextColor(hText,GUI_BLUE);
    //TEXT_SetBkColor(hText,GUI_WHITE);
    return hText;

}

WM_HWIN CreatePDA_IconMenu(void);



WM_HWIN CreatePDA_IconMenu(void)
{
  WM_HWIN hWin;	
  WM_HWIN hText;
  WM_HTIMER hTimer;
  
  //int hour=15;
  //int min=34;
  //int sec=29;
  
  
  WM_SetCreateFlags(WM_CF_MEMDEV);
  GUI_UC_SetEncodeUTF8();
  WIDGET_SetDefaultEffect(&WIDGET_Effect_Simple);

  
            
  hWin = ICONVIEW_CreateEx(0, 25, 240, 295, 
							   WM_HBKWIN, WM_CF_SHOW | WM_CF_HASTRANS, 
							   0, GUI_ID_ICONVIEW0, 65, 75);

  ICONVIEW_SetFont(hWin,&GUI_Font_Song_16);
 
  
  for (int i = 0; i < GUI_COUNTOF(_aBitmapItem); i++) 
  {
	   ICONVIEW_AddBitmapItem(hWin, _aBitmapItem[i].pBitmap, _aBitmapItem[i].pText);
       ICONVIEW_SetTextColor(hWin,i,GUI_BLACK);
  }

   
  //CreatHeaderWidget(WM_HWIN hTargetWin);
  
  ICONVIEW_SetBkColor(hWin, ICONVIEW_CI_SEL, GUI_BLUE | 0xC0000000);
  ICONVIEW_SetFrame(hWin,GUI_COORD_X,15);
  ICONVIEW_SetFrame(hWin,GUI_COORD_Y,70);
  
  ICONVIEW_SetSpace(hWin,GUI_COORD_X,10);
  ICONVIEW_SetSpace(hWin,GUI_COORD_Y,35);

 
  //GUI_SetPenSize(4);
  //GUI_SetColor(GUI_GREEN);
  //GUI_DrawHLine(27,5,145);


  g_hWin_task=GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbTaskDialog, WM_HBKWIN, 0, 0);
  hTimer = WM_CreateTimer(g_hWin_task, 0, 2000, 0);
  g_hWin_TimeBar=TimeBarDisp();
  g_hWin_Date=DateBarDisp();
  WM_SetFocus(hWin);
  WM_SetCallback(WM_HBKWIN, _cbIconWin);
  return hWin;
}










