/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "includes.h"

//#define PAGE_SWITCH (WM_USER+0)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
#if 0
//任务栏资源ID　
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_1     (GUI_ID_USER + 0x02)
#define ID_TEXT_2     (GUI_ID_USER + 0x03)
#define ID_TEXT_3     (GUI_ID_USER + 0x04)
#define ID_TEXT_4     (GUI_ID_USER + 0x05)

#define ID_TEXT_5     (GUI_ID_USER + 0x06)
#define ID_TEXT_6     (GUI_ID_USER + 0x07)
#define ID_TEXT_7     (GUI_ID_USER + 0x08) 
#define ID_TEXT_8     (GUI_ID_USER + 0x09) 
#define ID_LISTVIEW_0 (GUI_ID_USER + 0x0A) 
#define ID_TEXT_9     (GUI_ID_USER + 0x0B) 
#define ID_TEXT_10    (GUI_ID_USER + 0x0C)
//#define ID_TEXT_10    (GUI_ID_USER + 0x0C) 
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmSysSet;
extern GUI_CONST_STORAGE GUI_BITMAP bmmonitor;

extern GUI_CONST_STORAGE GUI_BITMAP bmmeter;

extern GUI_CONST_STORAGE GUI_BITMAP bmprotocal;
extern GUI_CONST_STORAGE GUI_BITMAP bmhelp;
extern GUI_CONST_STORAGE GUI_BITMAP bmSysInfo;




//icon信息结构体
typedef struct {
  const GUI_BITMAP * pBitmap;
  const char       * pText;
} BITMAP_ITEM;





//任务栏资源列表
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect,  NULL,           ID_WINDOW_0,  0,   0, 240, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect,    " ",            ID_TEXT_0,    3,   4, 40,  15, 0, 0x0, 0 }, //规约
  { TEXT_CreateIndirect,    " " ,           ID_TEXT_1,    55,  4, 50,  15, 0, 0x0, 0 }, //通道
  //{ TEXT_CreateIndirect,    " " ,           ID_TEXT_5,    75,  3, 35,  15, 0, 0x0, 0 }, //蜂鸣器
  { TEXT_CreateIndirect,    " ",            ID_TEXT_6,    110, 5, 40,  15, 0, 0x0, 0 }, //内存卡
  { TEXT_CreateIndirect,    DownloadIcon,   ID_TEXT_2,    156, 4, 17,  17, 0, 0x0, 0 }, //下行
  { TEXT_CreateIndirect,    UploadIcon,     ID_TEXT_3,    166, 4, 17,  17, 0, 0x0, 0 }, //上行
  { TEXT_CreateIndirect,    " ",            ID_TEXT_4,    196, 4, 42,  25, 0, 0x0, 0 }, //电池电量
};



static const BITMAP_ITEM _aBitmapItem[] = 
{
  
  {&bmSysSet,     CommParaSetText  },  //通信参数设置
  {&bmmeter,      ReadMeterText    },  //常用抄表 
  {&bmprotocal,   CommStdTestText  },  //通信规约调试
  {&bmmonitor,    MonitorText      },  //监控
  {&bmSysInfo,    SysInfo          },  //系统信息
  {&bmhelp,       About            }

};


WM_HWIN TSK_Get_Upload_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_2);
}

WM_HWIN TSK_Get_Download_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_3);
}

WM_HWIN TSK_Get_Protocol_Text()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
}
#if 0
void TSK_Set_BeepOn(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_5);
    TEXT_SetText(hItem, BeepOn);
}

void TSK_Set_BeepOff(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_5);
    TEXT_SetText(hItem, BeepOff);
}
#endif

void TSK_SetProtocol_97(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
    TEXT_SetText(hItem, "DL-97");
}

void TSK_SetProtocol_07(void)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
    TEXT_SetText(hItem, "DL-07");
}



#if 0
WM_HWIN TSK_GetWireless()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_10);
}
#endif


WM_HWIN TSK_Get_Battery()
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_4);
}

void TSK_Disp_RF(void)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_1);
    TEXT_SetText(hItem, TSK_RF);
}

void TSK_Disp_IR(void)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_1);
    TEXT_SetText(hItem, TSK_IR);
}

void TSK_Disp_NULL(void)
{
    WM_HWIN hItem;
    
    hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_1);
    TEXT_SetText(hItem, "");
}

WM_HWIN TSK_GetSD(void)
{
    return WM_GetDialogItem(g_hWin_task,ID_TEXT_6);
}

void TSK_Battery_Charge(int count)
{
    WM_HWIN hItem;
    hItem = WM_GetDialogItem(g_hWin_task,ID_TEXT_4);
    TEXT_SetFont(hItem,&GUI_Font_Battery_40);
    switch(count)
    {
        case 0:
            TEXT_SetText(hItem, Battery_20);
            break;
        case 2:
            TEXT_SetText(hItem, Battery_40);
            break;
        case 4:
            TEXT_SetText(hItem, Battery_60);
            break;
        case 6:
            TEXT_SetText(hItem, Battery_80);
            break;
        case 8:
            TEXT_SetText(hItem, Battery_100);
            break;
        default:
            break;
    }
    TEXT_SetTextColor(hItem, GUI_GREEN);
}

void TSK_Disp_PLC(void)
{
    WM_HWIN hItem;

    
    hItem = WM_GetDialogItem(g_hWin_task,ID_TEXT_1);

    if(PLC_STATE_MONITOR == g_sys_ctrl.plc_state)
    {
        TEXT_SetText(hItem, "PLC-M");
    }
    else if(PLC_STATE_METER_READ == g_sys_ctrl.plc_state)
    {
        TEXT_SetText(hItem, "PLC-R");
    }
    else if(PLC_STATE_READ_NODE == g_sys_ctrl.plc_state)
    {
        TEXT_SetText(hItem, "PLC-N");
    }
}

void TSK_Disp_Protocol(void)
{
    WM_HWIN hItem;

    
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_0);
    
    if(DL645_2007 == g_rom_para.protocol)
    {
        TEXT_SetText(hItem,Protocol_07);
    }
    else if(DL645_1997 == g_rom_para.protocol)
    {
        TEXT_SetText(hItem,Protocol_97);
    }
}

void TSK_Disp_Channel(void)
{
    if(CHANNEL_RF == g_rom_para.channel)
    {
        TSK_Disp_RF();
    }
    else if(CHANNEL_IR == g_rom_para.channel)
    {
        TSK_Disp_IR();
    }
    else if(CHANNEL_PLC == g_rom_para.channel)
    {
        TSK_Disp_PLC();
    }
    else
    {
        TSK_Disp_NULL();
    }
}

void GUI_Msg_Download(u16 sw)
{
    WM_HWIN hItem;
    static u32 i = 0;
    /*数据发送*/
    
    if(ON == sw)
    {
        i = ICON_FLOW_FLASH_TIMEOUT;
        hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_2);
        TEXT_SetTextColor(hItem, GUI_YELLOW);
    }
    else
    {
        if(i == 0xffffffff)
        {
            //i--;
        }
        else if(i)
        {
            i--;
        }
        else
        {
            hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_2);
            TEXT_SetTextColor(hItem, GUI_WHITE);//GUI_GREEN);
            i = 0xffffffff;
        }
    }
        
 }


void GUI_Msg_Upload(u16 sw)
{
    WM_HWIN hItem;
    static u32 i;
    
    if(ON == sw)
    {
        i = ICON_FLOW_FLASH_TIMEOUT;
        hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_3);
        TEXT_SetTextColor(hItem, GUI_GREEN);
    }
    else
    {
        if(i == 0xffffffff)
        {
            //i--;
            
        }
        else if(i)
        {
            i--;
        }
        else
        {
            hItem = WM_GetDialogItem(g_hWin_task, ID_TEXT_3);
            TEXT_SetTextColor(hItem, GUI_WHITE );//GUI_GREEN);
            i = 0xffffffff;
        }               
    }
}


void Battery_State(int pwr_val)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(g_hWin_task,ID_TEXT_4);
    TEXT_SetFont(hItem,&GUI_Font_Battery_40);
    if(pwr_val < 2166)
    {
        TEXT_SetText(hItem,Battery_00);
        TEXT_SetTextColor(hItem,GUI_RED);
    }
    
    else if((pwr_val > 2171)&&(pwr_val < 2229))
    {
        TEXT_SetText(hItem,Battery_20);
        TEXT_SetTextColor(hItem,GUI_RED);
    }
    else if((pwr_val >= 2234)&&(pwr_val < 2291))
    {
        TEXT_SetText(hItem,Battery_40);
        TEXT_SetTextColor(hItem,GUI_YELLOW);
    }
    else if((pwr_val >= 2296)&&(pwr_val < 2415))
    {
        TEXT_SetText(hItem,Battery_60);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }
    else if((pwr_val >= 2420)&&(pwr_val < 2480))
    {
        TEXT_SetText(hItem,Battery_80);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }
    else if(pwr_val >= 2485)
    {
        TEXT_SetText(hItem,Battery_100);
        //TEXT_SetText(hItem,Battery_Charge);
        TEXT_SetTextColor(hItem,GUI_GREEN);
    }



}

//任务栏回调函数

static void _cbTaskDialog(WM_MESSAGE * pMsg) 
{

  WM_HWIN hItem;
  int widget_id;
  
  switch (pMsg->MsgId) 
  {
      case WM_INIT_DIALOG:
        GUI_UC_SetEncodeUTF8();
        WINDOW_SetBkColor(pMsg->hWin, GUI_GRAY);
        
        hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_2);
        TEXT_SetTextColor(hItem,GUI_WHITE);
        
        hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_3);
        TEXT_SetTextColor(hItem,GUI_WHITE);

        //TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        //TEXT_SetTextColor(hItem, GUI_WHITE);

        hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_1);

        if(CHANNEL_PLC == g_rom_para.channel)
        {
            if(PLC_STATE_MONITOR == g_sys_ctrl.plc_state)
            {
                TEXT_SetText(hItem, "PLC-M");
            }
            else if(PLC_STATE_METER_READ == g_sys_ctrl.plc_state)
            {
                TEXT_SetText(hItem, "PLC-R");
            }
            else if(PLC_STATE_READ_NODE == g_sys_ctrl.plc_state)
            {
                TEXT_SetText(hItem, "PLC-N");
            }
        }        
        else if(CHANNEL_RF == g_rom_para.channel)
        {
            TEXT_SetText(hItem, TSK_RF);
        }
        else if(CHANNEL_IR == g_rom_para.channel)
        {
            TEXT_SetText(hItem, TSK_IR);
        }
        else
        {
            TEXT_SetText(hItem, "");
        }
        
        hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_0);

        if(g_rom_para.protocol==DL645_2007)
        {
            TEXT_SetText(hItem,Protocol_07);
        }
        else if(g_rom_para.protocol==DL645_1997)
        {
            TEXT_SetText(hItem,Protocol_97);
        }
#if 0        
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        TEXT_SetTextColor(hItem, GUI_WHITE);
        if(ON == g_rom_para.beep_switch)
        {
            TEXT_SetText(hItem, BeepOn);
        }
        else
        {
            TEXT_SetText(hItem, BeepOff);
        }
#endif
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        TEXT_SetTextColor(hItem, GUI_DARKGRAY);
      
        //hItem=WM_GetDialogItem(pMsg->hWin,ID_TEXT_7); 
        //TEXT_SetFont(hItem,&GUI_Font_Battery_40);
        //Battery_State(pMsg,g_sys_ctrl.pwrValue);
        break;
     // case WM_TIMER:
       // Battery_State(pMsg,g_sys_ctrl.pwrValue);
        //WM_RestartTimer(pMsg->Data.v, 1000);
        //break;

      default:
        WM_DefaultProc(pMsg);
        break;
  }
}


/*********************************************************************
*
*       _cbDialog
*/

static void _cbIconWin(WM_MESSAGE * pMsg) 
{
	int     NCode;
	int     Id;
	int IconViewIndex;//索引
	WM_HWIN hIconView;
    WM_HWIN hItem;
	hIconView = g_hWin_menu;
	IconViewIndex=ICONVIEW_GetSel(hIconView);
	switch (pMsg->MsgId) 
	{   

        case WM_INIT_DIALOG:
            break;
		case WM_PAINT: 
			GUI_SetBkColor(0xb2c7ca);
			GUI_Clear();
			break;
		case WM_KEY:
            
           // if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)
            {
            
			switch(((WM_KEY_INFO*)(pMsg->Data.p))->Key)
			{
				case GUI_KEY_ENTER:
					switch(IconViewIndex)
					{	
						case 0:
							g_hWin_para = CreateCommParaSet();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            //WM_SetFocus(g_hWin_para);
                            hItem = CPS_Set_Proto();
                            WM_SetFocus(hItem);
                            GUI_Color_Change(g_hWin_para, ID_EDIT_0, 8);
							break;
                            
						case 2:
							g_hWin_ProtoDbg = CreateCommStdTest();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            //WM_SetFocus(g_hWin_ProtoDbg);
                            hItem = CPT_Get_Speed();
                            WM_SetFocus(hItem);
                            GUI_Color_Change(g_hWin_ProtoDbg, ID_EDIT_0, 6);
							break;
						case 4:
							g_hWin_SysInfo=CreateSysInfo();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_SysInfo);
							break;
                            
                        case 1:
			                g_hWin_ReadMeter=CreateReadMeter();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            //WM_SetFocus(g_hWin_ReadMeter);
                            hItem = RMD_Get_MeterNum();
                            WM_SetFocus(hItem);
                            //RMD_Color_Change();
                            GUI_Color_Change(g_hWin_ReadMeter, ID_EDIT_0, 3);
							break;
                            
						case 3:
							g_hWin_monitor=CreateMonitor();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_monitor);
							break;
                            
                        case 5:
                            g_hWin_about=Createabout();
                            WM_BringToBottom(g_hWin_msg);
                            WM_HideWindow(g_hWin_TimeBar);
                            WM_HideWindow(g_hWin_Date);
                            WM_SetFocus(g_hWin_about);
                            break;
						
						default:
							break;
					}
				break;
			}
            }
			break;
		default:
			WM_DefaultProc(pMsg);
			break;
	}
}


/*********************************************************************
*
*       Public code
*
**********************************************************************
*/


WM_HWIN TimeBarDisp(void)
{
    WM_HWIN hText;
    hText=TEXT_CreateEx(20,30,200,31,g_hWin_menu,WM_CF_SHOW,TEXT_CF_HCENTER,ID_TEXT_8,"00:00");
    TEXT_SetFont(hText,&GUI_Fontcn27);
    TEXT_SetTextColor(hText,GUI_DARKGRAY);
    return hText;
}


WM_HWIN DateBarDisp(void)
{
    WM_HWIN hText;
    hText=TEXT_CreateEx(20,63,200,21,g_hWin_menu,WM_CF_SHOW,TEXT_CF_HCENTER,ID_TEXT_9," ");
    TEXT_SetFont(hText,&GUI_Fontdate20);
    //TEXT_SetTextColor(hText,GUI_BLUE);
    //TEXT_SetBkColor(hText,GUI_WHITE);
    return hText;

}

WM_HWIN CreatePDA_IconMenu(void);



WM_HWIN CreatePDA_IconMenu(void)
{
  WM_HWIN hWin;	
  WM_HWIN hText;
  WM_HTIMER hTimer;
    
  WM_SetCreateFlags(WM_CF_MEMDEV);
  GUI_UC_SetEncodeUTF8();
  WIDGET_SetDefaultEffect(&WIDGET_Effect_Simple);
        
  hWin = ICONVIEW_CreateEx(0, 25, 240, 295, 
							   WM_HBKWIN, WM_CF_SHOW | WM_CF_HASTRANS, 
							   0, GUI_ID_ICONVIEW0, 65, 75);

  ICONVIEW_SetFont(hWin,&GUI_Font_Song_16);
 
  
  for (int i = 0; i < GUI_COUNTOF(_aBitmapItem); i++) 
  {
	   ICONVIEW_AddBitmapItem(hWin, _aBitmapItem[i].pBitmap, _aBitmapItem[i].pText);
       ICONVIEW_SetTextColor(hWin,i,GUI_BLACK);
  }
  
  ICONVIEW_SetBkColor(hWin, ICONVIEW_CI_SEL, GUI_BLUE | 0xC0000000);
  ICONVIEW_SetFrame(hWin,GUI_COORD_X,15);
  ICONVIEW_SetFrame(hWin,GUI_COORD_Y,70);
  
  ICONVIEW_SetSpace(hWin,GUI_COORD_X,10);
  ICONVIEW_SetSpace(hWin,GUI_COORD_Y,35);

 
  //GUI_SetPenSize(4);
  //GUI_SetColor(GUI_GREEN);
  //GUI_DrawHLine(27,5,145);


  g_hWin_task=GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbTaskDialog, WM_HBKWIN, 0, 0);
  //hTimer = WM_CreateTimer(g_hWin_task, 0, 2000, 0);
  g_hWin_TimeBar=TimeBarDisp();
  g_hWin_Date=DateBarDisp();
  WM_SetFocus(hWin);
  WM_SetCallback(WM_HBKWIN, _cbIconWin);
  return hWin;
}










