/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x76)

#define ID_BUTTON_0   (GUI_ID_USER + 0x77)
#define ID_BUTTON_1   (GUI_ID_USER + 0x78)
#define ID_BUTTON_2   (GUI_ID_USER + 0x79)
#define ID_BUTTON_3   (GUI_ID_USER + 0x7A)

#define ID_DROPDOWN_0 (GUI_ID_USER + 0x7B)

#define ID_TEXT_0     (GUI_ID_USER + 0x7C)
#define ID_TEXT_1     (GUI_ID_USER + 0x7D)
#define ID_TEXT_2     (GUI_ID_USER + 0x7E)
#define ID_TEXT_3     (GUI_ID_USER + 0x7F)
#define ID_TEXT_4     (GUI_ID_USER + 0x80)
#define ID_TEXT_5     (GUI_ID_USER + 0x81)
#define ID_TEXT_6     (GUI_ID_USER + 0x82)
#define ID_TEXT_7     (GUI_ID_USER + 0x83)
#define ID_TEXT_8     (GUI_ID_USER + 0x84)  
#define ID_TEXT_9     (GUI_ID_USER + 0x85)  
#define ID_TEXT_10    (GUI_ID_USER + 0x86)  
#define ID_TEXT_11    (GUI_ID_USER + 0x87) 

#define ID_EDIT_0     (GUI_ID_USER + 0x88)
#define ID_EDIT_1     (GUI_ID_USER + 0x89)
#define ID_EDIT_2     (GUI_ID_USER + 0x8A)
#define ID_EDIT_3     (GUI_ID_USER + 0x8B)
#define ID_EDIT_4     (GUI_ID_USER + 0x8C)
#define ID_EDIT_5     (GUI_ID_USER + 0x8D)

#define ID_PROGBAR_0  (GUI_ID_USER + 0x8E)

#define ID_BUTTON_4   (GUI_ID_USER + 0x8F)//自动获取表号

//static int PressCount = 0;



/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

//自动获取电表表号以及波特率
//获取参数
static const char GetMeterNum[]="F1\xe8\x8e\xb7\xe5\x8f\x96\xe8\xa1\xa8\xe5\x8f\xb7";


//消息内容
static const char Msg[]="#\xe6\xb6\x88\xe6\x81\xaf\xe5\x86\x85\xe5\xae\xb9";

//电表表号
static const char MeterNum[]="\xe7\x94\xb5\xe8\xa1\xa8\xe8\xa1\xa8\xe5\x8f\xb7";


//抄表项目
static const char ReadMeterSel[]="\xe6\x8a\x84\xe8\xa1\xa8\xe9\xa1\xb9\xe7\x9b\xae";


//当前正向有功电能
static const char Positive[]="\xe5\xbd\x93\xe5\x89\x8d\xe6\xad\xa3\xe5\x90\x91\xe6\x9c\x89\xe5\x8a\x9f\xe7\x94\xb5\xe8\x83\xbd";


//当前反向有功电能
static const char Negative[]="\xe5\xbd\x93\xe5\x89\x8d\xe5\x8f\x8d\xe5\x90\x91\xe6\x9c\x89\xe5\x8a\x9f\xe7\x94\xb5\xe8\x83\xbd";


//日冻结正向有功电能
static const char DayPositive[]="\xe6\x97\xa5\xe5\x86\xbb\xe7\xbb\x93\xe6\xad\xa3\xe5\x90\x91\xe6\x9c\x89\xe5\x8a\x9f\xe7\x94\xb5\xe8\x83\xbd";


//日冻结反向有功电能
static const char DayNegative[]="\xe6\x97\xa5\xe5\x86\xbb\xe7\xbb\x93\xe5\x8f\x8d\xe5\x90\x91\xe6\x9c\x89\xe5\x8a\x9f\xe7\x94\xb5\xe8\x83\xbd";

//总电量    ----
static const char TotalVal[]="\xe6\x80\xbb\xe7\x94\xb5\xe9\x87\x8f";

//抄表
static const char ReadMeter[]="F2\xe6\x8a\x84\xe8\xa1\xa8";

//保存
static const char Save[]="\xe4\xbf\x9d\xe5\xad\x98";

//取消
static const char Cancel[]="\xe5\x8f\x96\xe6\xb6\x88";




const char gc_messageBoxText[][32] = 
{
    "Address Error!",
    "Data Flag Error!",
    "Protocol Error!",
};






//
//
//
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
    { WINDOW_CreateIndirect, "ReadMeter", ID_WINDOW_0, 0, 0, 240, 295, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, GetMeterNum, ID_BUTTON_1, 14, 7, 90, 30, 0, 0x0, 0 },

    { BUTTON_CreateIndirect, ReadMeter, ID_BUTTON_0, 147, 7, 80, 30, 0, 0x0, 0 },
    { TEXT_CreateIndirect, MeterNum, ID_TEXT_0, 8, 50, 72, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_0, 89, 46, 136, 20, 0, 0x64, 0 },
        
    { TEXT_CreateIndirect, ReadMeterSel, ID_TEXT_1, 8, 74, 69, 20, 0, 0x0, 0 },
    { DROPDOWN_CreateIndirect, NULL, ID_DROPDOWN_0, 89, 73, 136, 19, 0, 0x0, 0 },
        
    { TEXT_CreateIndirect, TotalVal, ID_TEXT_2, 23, 103, 49, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_1, 89, 101, 106, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "kWh", ID_TEXT_7, 199, 101, 35, 20, 0, 0x0, 0 },
        
    { TEXT_CreateIndirect, "\xe5\xb0\x96", ID_TEXT_3, 23, 129, 80, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_2, 89, 128, 106, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "kWh", ID_TEXT_8, 199, 128, 35, 20, 0, 0x0, 0 },
        
    { TEXT_CreateIndirect, "\xe5\xb3\xb0", ID_TEXT_4, 23, 158, 80, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_3, 89, 156, 106, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "kWh", ID_TEXT_9, 199, 156, 35, 20, 0, 0x0, 0 },
        
    { TEXT_CreateIndirect, "\xe5\xb9\xb3", ID_TEXT_5, 23, 187, 80, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_4, 89, 185, 106, 20, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "kWh", ID_TEXT_10, 199, 185, 35, 20, 0, 0x0, 0 },
        
    { TEXT_CreateIndirect, "\xe8\xb0\xb7", ID_TEXT_6, 23, 211, 80, 20, 0, 0x0, 0 },
    { EDIT_CreateIndirect, NULL, ID_EDIT_5, 89, 209, 106, 20, 0, 0x64, 0 },    
    { TEXT_CreateIndirect, "kWh", ID_TEXT_11, 199, 209, 35, 20, 0, 0x0, 0 },
        
    { BUTTON_CreateIndirect, Save, ID_BUTTON_2, 8, 264, 55, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, Msg, ID_BUTTON_4, 74, 264, 90, 25, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, Cancel, ID_BUTTON_3, 175, 264, 55, 25, 0, 0x0, 0},
    { PROGBAR_CreateIndirect, NULL,   ID_PROGBAR_0, 8, 237, 220, 20, 0, 0x0, 0},
};



//u8 rmd[20];


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

const u32 c_645DidoDef[2][PLC_CTRL_MAX_NUM] = 
{ 
    //97规约
    {0x901f,    0x902f,     0x9410,     0x9420,5,6,7,8,9,10,11,12,13,14,15,16},
    //07规约
    {0x0001ff00,0X0002ff00, 0X0001ff01, 0X0002ff01,4,5,6,7,8,9,10,11,12,13,14,15,}
};

WM_HWIN RMD_Get_PROGBAR()
{    
     return WM_GetDialogItem(g_hWin_ReadMeter, ID_PROGBAR_0);            
}


static u8 RMD_Get_Para(WM_MESSAGE *pMsg)
{   
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
    u8  i;
    u8  dropdown_selnum;
    u8 rmd[GUI_645_ADDR_LENGTH+2];
 
    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
    EDIT_GetText(hItem, rmd, GUI_645_ADDR_LENGTH+1);

    if(strlen(rmd) != GUI_645_ADDR_LENGTH)
    {
        //error proc
        //GUI_MessageBox()
        //MESSAGEBOX_Create("dst addr error!", "error", 0);
        //EDIT_SetText(hItem, "11111");
        ERROR_BOX(GUI_MSBOX_ADDR_ERROR);
        return DEV_ERROR;
    }

    if(DEV_OK != GUI_GetMeterAddr(rmd))
    {
        return DEV_ERROR;
    }
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_0);
    dropdown_selnum=DROPDOWN_GetSel(hItem);  
    
    if(g_sys_register_para.plcProtocol==DL_T_07)
    {        
        memcpy(g_send_para_pkg.dataFlag,
            &c_645DidoDef[g_sys_register_para.plcProtocol][dropdown_selnum],
            4);
        
        g_send_para_pkg.ctlCode=0x11;
    }
    else if(g_sys_register_para.plcProtocol==DL_T_97)
    {
        memcpy(g_send_para_pkg.dataFlag,
            &c_645DidoDef[g_sys_register_para.plcProtocol][dropdown_selnum],
            2);
        g_send_para_pkg.ctlCode=0x01; 

    }
    else
    {
        return DEV_ERROR;
    }

    g_send_para_pkg.cmdType = PLC_CMD_TYPE_COMMON;
    
    return DEV_OK;

}



void RMD_proc_resp_data(void)
{
    WM_HWIN hItem;
    u8 * pbuf;
    u32 len;

    pbuf = g_plc_prm.data_buf;
    len = g_plc_prm.data_len;

    if(g_hWin_ReadMeter != WM_HWIN_NULL)
    {
        if(g_send_para_pkg.cmdType == PLC_CMD_BROAD_READ)
        {
            if(len == 6)
            {
                hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_0);
                EDIT_SetText(hItem, 
                    (const char*)GUI_hex2MeterAddrStr(pbuf, len));
            }
            return;
        }
       
        //SWITCH(DATA FLAG)
        if(g_plc_prm.data_len >= 4)
        {
            hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_1);
            EDIT_SetText(hItem, 
                (const char*)GUI_hex2PowerDataStr(pbuf, len));
            pbuf += 4;
            len -= 4;
        }
        else
        {
            return;
        }

        if(g_plc_prm.data_len >= 4)
        {
            hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_2);
            EDIT_SetText(hItem, 
                (const char*)GUI_hex2PowerDataStr(pbuf, len));
            pbuf += 4;
            len -= 4;
        }
        else
        {
            return;
        }

        if(g_plc_prm.data_len >= 4)
        {
            hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_3);
            EDIT_SetText(hItem, 
                (const char*)GUI_hex2PowerDataStr(pbuf, len));
            pbuf += 4;
            len -= 4;
        }
        else
        {
            return;
        }

        if(g_plc_prm.data_len >= 4)
        {
            hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_4);
            EDIT_SetText(hItem, 
                (const char*)GUI_hex2PowerDataStr(pbuf, len));
            pbuf += 4;
            len -= 4;
        }
        else
        {
            return;
        }

        if(g_plc_prm.data_len >= 4)
        {
            hItem = WM_GetDialogItem(g_hWin_ReadMeter, ID_EDIT_5);
            EDIT_SetText(hItem, 
                (const char*)GUI_hex2PowerDataStr(pbuf, len));
            pbuf += 4;
            len -= 4;
        }
        else
        {
            return;
        }                
        
    }
}


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Edit'
    //
    GUI_UC_SetEncodeUTF8();

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
    BUTTON_SetBkColor(hItem,0,GUI_GREEN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
    BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_4);
    BUTTON_SetBkColor(hItem,0,GUI_CYAN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);


    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    //EDIT_SetText(hItem, "0");
    EDIT_SetText(hItem, (const char *)GUI_hex2MeterAddrStr(g_sys_control.recentMeterAddr, 6));
    //WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "0");
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "0");
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "0");
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "0");
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    WM_DisableWindow(hItem);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, "0");
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    WM_DisableWindow(hItem);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, Positive);
    DROPDOWN_AddString(hItem, Negative);
    DROPDOWN_AddString(hItem, DayPositive);
    DROPDOWN_AddString(hItem, DayNegative);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0);
    PROGBAR_SetBarColor(hItem,0,GUI_GREEN);
    //PROGBAR_SetBarColor(hItem,1,GUI_WHITE);
    
    break;
  case WM_PAINT:
    //GUI_BMP_Draw(&bm_Upload,160,4);
    //GUI_Clear();
    
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) 
    {
        case ID_DROPDOWN_0:
            hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
            WM_DisableWindow(hItem);
            break;
        case ID_EDIT_0:
            hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
            WM_EnableWindow(hItem);
            break;
        default:
            break;
    }
    break;

  case WM_KEY:
    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)//按键释放。added on 2015.1.4
    {
        Id=WM_GetId(pMsg->hWinSrc);

        int TimeCount;//进度条参数
            
        if(Id==ID_EDIT_0)
        {
            if((((WM_KEY_INFO *)(pMsg->Data.p))->Key)==GUI_KEY_ESCAPE)
            {
                hItem=WM_GetDialogItem(pMsg->hWin,ID_DROPDOWN_0);
                WM_SetFocus(hItem);
            }
            else if((((WM_KEY_INFO*)(pMsg->Data.p))->Key) == GUI_KEY_YELLOW)
            {
                WM_DeleteWindow(g_hWin_ReadMeter);
                g_hWin_ReadMeter=HBWIN_NULL;
                WM_SetFocus(g_hWin_menu);
                break;
            }
            else
            {
                break;
            }
        }
        switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
        {
            case GUI_KEY_YELLOW:
                WM_DeleteWindow(g_hWin_ReadMeter);
                g_hWin_ReadMeter=HBWIN_NULL;
                WM_BringToBottom(g_hWin_msg);
                WM_HideWindow(g_hWin_msg);
                WM_SetFocus(g_hWin_menu);
                break;
            case GUI_KEY_F1: /*获取表号*/
                //hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
                //EDIT_SetText(hItem,"003619000000");
                g_send_para_pkg.cmdType = PLC_CMD_BROAD_READ;
                g_sys_control.guiState = GUI_PLC_MSG_READ;                        
                OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                break;
                
            case '#':
               // g_hWin_ReadMeterMsg=CreateReadMeterMessage();
               // WM_ShowWindow(g_hWin_ReadMeterMsg);
               // WM_SetFocus(g_hWin_ReadMeterMsg);
                WM_BringToTop(g_hWin_msg);
                WM_ShowWindow(g_hWin_msg);                    
                WM_SetFocus(g_hWin_msg);
                break;
                
            case GUI_KEY_F2:
#if 0                
                ButtonBlink(pMsg,ID_BUTTON_0);
                hItem=WM_GetDialogItem(pMsg->hWin,ID_PROGBAR_0);
                for(TimeCount=1;TimeCount<=10;TimeCount++)
                {
                    GUI_Delay(100);
                    PROGBAR_SetValue(hItem,10*TimeCount);
                }
#endif                
                if(DEV_OK == RMD_Get_Para(pMsg))//获取参数数据
                {
                    g_sys_control.guiState = GUI_PLC_MSG_READ;
                    OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                }
           
                break;
        }
    }
    break;

  case WM_MSG_CLOSE:
    WM_DeleteWindow(g_hWin_ReadMeter);
	break;
    
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateReadMeter
*/
WM_HWIN CreateReadMeter(void);
WM_HWIN CreateReadMeter(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
