/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.20                          *
*        Compiled Mar 19 2013, 15:01:00                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x09)
#define ID_TEXT_1   (GUI_ID_USER + 0x0A)
#define ID_TEXT_2   (GUI_ID_USER + 0x0B)
#define ID_TEXT_3   (GUI_ID_USER + 0x0C)
#define ID_TEXT_4   (GUI_ID_USER + 0x0D)
#define ID_TEXT_5   (GUI_ID_USER + 0x0E)

#define ID_EDIT_0   (GUI_ID_USER + 0x0F)
#define ID_EDIT_1   (GUI_ID_USER + 0x10)
#define ID_EDIT_2   (GUI_ID_USER + 0x11)
#define ID_EDIT_3   (GUI_ID_USER + 0x12)
#define ID_EDIT_4   (GUI_ID_USER + 0x13)
#define ID_EDIT_5   (GUI_ID_USER + 0x14)

#define ID_BUTTON_0 (GUI_ID_USER + 0x15)
#define ID_BUTTON_1 (GUI_ID_USER + 0x16)
#define ID_TEXT_6   (GUI_ID_USER + 0x17)
#define ID_TEXT_7   (GUI_ID_USER + 0x18)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char Year[]  ="1-\xe5\xb9\xb4:";
static const char Month[] ="2-\xe6\x9c\x88:";
static const char Day[]   ="3-\xe6\x97\xa5:";
static const char Hour[]  ="4-\xe6\x97\xb6:";
static const char Minite[]="5-\xe5\x88\x86:";
static const char Second[]="6-\xe7\xa7\x92:";

static const char Confirm[]="\xe7\xa1\xae\xe5\xae\x9a";
static const char Cancel[] ="\xe5\x8f\x96\xe6\xb6\x88";

static const char TimeSet[]="\xe6\x97\xb6\xe9\x97\xb4\xe8\xae\xbe\xe7\xbd\xae(24\xe6\x97\xb6\xe5\x88\xb6)";
static const char TypeDirection[]="24\xe5\xb0\x8f\xe6\x97\xb6\xe6\xa0\xbc\xe5\xbc\x8f";
//\xe5\xb0\x8f \xe6\xa0\xbc\xe5\xbc\x8f小格式

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, HBWIN_NULL,ID_WINDOW_0, 0,   0,   240, 295, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Year,      ID_TEXT_0,   51,  43,  40,  20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Month,     ID_TEXT_1,   51,  79,  40,  20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Day,       ID_TEXT_2,   51,  114, 40,  20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Hour,      ID_TEXT_3,   51,  150, 40,  20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Minite,    ID_TEXT_4,   51,  187, 40,  20, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   Second,    ID_TEXT_5,   51,  222, 40,  20, 0, 0x0, 0 },
  { EDIT_CreateIndirect,   "year",    ID_EDIT_0,   110, 41,  80,  20, 0, 2, 0 },
  { EDIT_CreateIndirect,   "month",   ID_EDIT_1,   110, 77,  80,  20, 0, 2, 0 },
  { EDIT_CreateIndirect,   "day",     ID_EDIT_2,   110, 112, 80,  20, 0, 2, 0 },
  { EDIT_CreateIndirect,   "hour",    ID_EDIT_3,   110, 148, 80,  20, 0, 2, 0 },
  { EDIT_CreateIndirect,   "min",     ID_EDIT_4,   110, 185, 80,  20, 0, 2, 0 },
  { EDIT_CreateIndirect,   "sec",     ID_EDIT_5,   110, 220, 80,  20, 0, 2, 0 },
  { BUTTON_CreateIndirect, Confirm,   ID_BUTTON_0, 10,  259, 80,  25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, Cancel,    ID_BUTTON_1, 150, 261, 80,  25, 0, 0x0, 0 },
  { TEXT_CreateIndirect,   TimeSet,   ID_TEXT_6,   60,  12,  150, 20, 0, 0x0, 0 },
 // { TEXT_CreateIndirect,   TimeSet,   ID_TEXT_7,   50,  12, 120,  20, 0, 0x0, 0 }
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/



#if 1
void Time_From_Widget(unsigned char *time)
{
    WM_HWIN hItem;
    unsigned char TimeBuf[3];//每个控件中获取的字符串缓冲 
    //u8  time[7];
    
    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_5); 
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[0]=Hex2BcdChar(atoi(TimeBuf));
    
    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_4);     
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[1]=Hex2BcdChar(atoi(TimeBuf));
    
    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_3);     
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[2]=Hex2BcdChar(atoi(TimeBuf));

    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_2);     
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[4]=Hex2BcdChar(atoi(TimeBuf));
    
    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_1);    
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[5]=Hex2BcdChar(atoi(TimeBuf));
    
    hItem=WM_GetDialogItem(g_hWin_TimeSet,ID_EDIT_0);     
    EDIT_GetText(hItem,TimeBuf,TIME_CH_LEN);
    time[6]=Hex2BcdChar(atoi(TimeBuf));
      
}
#endif


static void Time_Init(WM_MESSAGE *pMsg)
{
    WM_HWIN hItem;
    u8 year[3], mon[3], day[3], date[3], hour[3], min[3], sec[3];
    sprintf(year, "%02x", g_rtc_time[YEAR_POS]);
    sprintf(mon, "%02x", g_rtc_time[MONTH_POS]);
    sprintf(date, "%02x", g_rtc_time[DATE_POS]);    
    sprintf(day, "%02x", g_rtc_time[DAY_POS]);            
    sprintf(hour, "%02x", g_rtc_time[HOUR_POS]);
    sprintf(min, "%02x", g_rtc_time[MIN_POS]);
    sprintf(sec, "%02x", g_rtc_time[SEC_POS]);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem,year);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, mon);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, date);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, hour);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem,min);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_5);
    EDIT_SetText(hItem, sec);
}


// USER START (Optionally insert additional static code)

static void _init_TimeSet_dialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0); 
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    BUTTON_SetBkColor(hItem, 0, GUI_GREEN);
    //BUTTON_Handle hObj,unsigned int Index,GUI_COLOR Color)
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1); 
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    BUTTON_SetBkColor(hItem, 0, GUI_YELLOW);

    Time_Init(pMsg);
  

}


void Disable_Edit(void)
{
    



}


static void Disable_Enable_Widget(WM_MESSAGE * pMsg)
{
   int Id;
   Id   = WM_GetId(pMsg->hWinSrc);
   switch(Id) 
   {
       case ID_EDIT_0:
           Enable_Widget(pMsg,ID_EDIT_0);
           Disable_Widget(pMsg,ID_EDIT_1);
           Disable_Widget(pMsg,ID_EDIT_2);
           Disable_Widget(pMsg,ID_EDIT_3);
           Disable_Widget(pMsg,ID_EDIT_4);
           Disable_Widget(pMsg,ID_EDIT_5);
           break;
       case ID_EDIT_1:
           Disable_Widget(pMsg,ID_EDIT_0);
           Enable_Widget(pMsg,ID_EDIT_1);
           Disable_Widget(pMsg,ID_EDIT_2);
           Disable_Widget(pMsg,ID_EDIT_3);
           Disable_Widget(pMsg,ID_EDIT_4);
           Disable_Widget(pMsg,ID_EDIT_5);
           break;
       case ID_EDIT_2:
           Disable_Widget(pMsg,ID_EDIT_0);
           Disable_Widget(pMsg,ID_EDIT_1);
           Enable_Widget(pMsg,ID_EDIT_2);
           Disable_Widget(pMsg,ID_EDIT_3);
           Disable_Widget(pMsg,ID_EDIT_4);
           Disable_Widget(pMsg,ID_EDIT_5);
           break;
       case ID_EDIT_3:
           Disable_Widget(pMsg,ID_EDIT_0);
           Disable_Widget(pMsg,ID_EDIT_1);
           Disable_Widget(pMsg,ID_EDIT_2);
           Enable_Widget(pMsg,ID_EDIT_3);
           Disable_Widget(pMsg,ID_EDIT_4);
           Disable_Widget(pMsg,ID_EDIT_5);
           break;
       case ID_EDIT_4:
           Disable_Widget(pMsg,ID_EDIT_0);
           Disable_Widget(pMsg,ID_EDIT_1);
           Disable_Widget(pMsg,ID_EDIT_2);
           Disable_Widget(pMsg,ID_EDIT_3);
           Enable_Widget(pMsg,ID_EDIT_4);
           Disable_Widget(pMsg,ID_EDIT_5);
           break;
       case ID_EDIT_5:
           Disable_Widget(pMsg,ID_EDIT_0);
           Disable_Widget(pMsg,ID_EDIT_1);
           Disable_Widget(pMsg,ID_EDIT_2);
           Disable_Widget(pMsg,ID_EDIT_3);
           Disable_Widget(pMsg,ID_EDIT_4);
           Enable_Widget(pMsg,ID_EDIT_5);
           break;
    }
}


// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) 
{
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  int i;
  switch (pMsg->MsgId) 
  {
      case WM_INIT_DIALOG:
        _init_TimeSet_dialog(pMsg);
        break;
        
      case WM_NOTIFY_PARENT:
        Disable_Enable_Widget(pMsg);
        break;
       
      case WM_KEY:
        if((((WM_KEY_INFO *)(pMsg->Data.p))->PressedCnt)==0)
        {
#if 0
            Id=WM_GetId(pMsg->hWinSrc);
            if((Id>=ID_EDIT_0)&&(Id<=ID_EDIT_5))
            {
                if((((WM_KEY_INFO*)(pMsg->Data.p))->Key) == GUI_KEY_ESCAPE)
                {
                    for(i=0;i<6;i++)
                    {
                        hItem=WM_GetDialogItem(pMsg->hWin,(ID_EDIT_0+i));
                        WM_DisableWindow(hItem);
                    }
                }
                else if((((WM_KEY_INFO*)(pMsg->Data.p))->Key) == GUI_KEY_YELLOW)
                {
                    WM_DeleteWindow(g_hWin_TimeSet);
                    g_hWin_TimeSet=HBWIN_NULL;
                    WM_SetFocus(g_hWin_para);
                    break;
                }
                else
                    break;

            }
#endif
            switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
            {
                case GUI_KEY_GREEN: /*保存重新设置的时间*/
                    Time_From_Widget(g_rtc_time);
                    
                    RTC_WriteTime(g_rtc_time);
                    //RTC2Text();
                    //Time_Init(pMsg);
                    break;
                //因为没有在edit中拦截消息，所以在edit中也可以直接删除窗口
                case GUI_KEY_YELLOW:
                    WM_DeleteWindow(g_hWin_TimeSet);
                    g_hWin_TimeSet=HBWIN_NULL;
                    WM_SetFocus(g_hWin_para);
                    break;
#if 0
                case '1':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_0);
                    WM_SetFocus(hItem);
                    break;
                case '2':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_1);
                    WM_SetFocus(hItem);
                    break;
                case '3':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_2);
                    WM_SetFocus(hItem);
                    break;
                case '4':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_3);
                    WM_SetFocus(hItem);
                    break;
                case '5':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_4);
                    WM_SetFocus(hItem);
                    break;
                case '6':
                    hItem=WM_GetDialogItem(pMsg->hWin,ID_EDIT_5);
                    WM_SetFocus(hItem);
                    break;
#endif
            }

        }
        break;
      default:
        WM_DefaultProc(pMsg);
        break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateTimeSet(void);
WM_HWIN CreateTimeSet(void) 
{
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_para, 0, 0);
  return hWin;
}





/*************************** End of file ****************************/



