/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x99)
#define ID_TEXT_0       (GUI_ID_USER + 0x6D)
#define ID_DROPDOWN_0   (GUI_ID_USER + 0x6E)
#define ID_BUTTON_0     (GUI_ID_USER + 0x6F)
#define ID_BUTTON_1     (GUI_ID_USER + 0x70)
#define ID_BUTTON_2     (GUI_ID_USER + 0x71)
#define ID_TEXT_1       (GUI_ID_USER + 0x72)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x73)
//#define ID_TEXT_2       (GUI_ID_USER + 0x74)
//#define ID_MULTIEDIT_1  (GUI_ID_USER + 0x75)
#define ID_BUTTON_3     (GUI_ID_USER + 0x76)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

//设置命令选择

static const char CmdSel[]="\xe8\xae\xbe\xe7\xbd\xae\xe9\x80\x89\xe6\x8b\xa9";

//发送数据
static const char SendData[]="\xe5\x8f\x91\xe9\x80\x81\xe6\x95\xb0\xe6\x8d\xae";

//接收数据
static const char RevData[]="\xe6\x8e\xa5\xe6\x94\xb6\xe6\x95\xb0\xe6\x8d\xae";

//设为监控器
static const char Monitor[]="\xe8\xae\xbe\xe4\xb8\xba\xe7\x9b\x91\xe6\x8e\xa7\xe5\x99\xa8";

//设为抄控器

static const char Copy[]="\xe8\xae\xbe\xe4\xb8\xba\xe6\x8a\x84\xe6\x8e\xa7\xe5\x99\xa8";

//读取模块状态
static const char ReadModule[]="\xe8\xaf\xbb\xe5\x8f\x96\xe6\xa8\xa1\xe5\x9d\x97\xe7\x8a\xb6\xe6\x80\x81";

//取消
static const char Cancel[]="\xe5\x8f\x96\xe6\xb6\x88";

//数据
static const char Data[]="\xe6\x95\xb0\xe6\x8d\xae";


/*********************************************************************
*
*       _aDialogCreate
*/

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "WaveCarriorSet", ID_WINDOW_0, 0, 0, 240, 295, 0, 0x0, 0 },
  { TEXT_CreateIndirect, CmdSel, ID_TEXT_0, 12, 5, 70, 20, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 12, 26, 128, 19, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "F1\xe6\xb8\x85\xe9\x99\xa4", ID_BUTTON_0, 171, 21, 63, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "F2\xe8\xae\xbe\xe7\xbd\xae",  ID_BUTTON_3, 171, 50, 63,25,  0, 0x0, 0},
  { BUTTON_CreateIndirect, Cancel, ID_BUTTON_1, 175, 264, 55, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "\xe5\x8f\x91\xe9\x80\x81", ID_BUTTON_2, 8, 264, 55, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect,    Data, ID_TEXT_1, 17, 58, 77, 20, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 11, 80, 225, 175, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, RevData, ID_TEXT_2, 10, 160, 80, 20, 0, 0x0, 0 },
  //{ MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_1, 9, 175, 227, 84, 0, 0x0, 0 },
};


/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

/**************************************************************
*
*                     初始化对话框
*
***************************************************************/
static void _init_dialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_3);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_2);
    BUTTON_SetBkColor(hItem,0,GUI_GREEN);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
    BUTTON_SetBkColor(hItem,0,GUI_YELLOW);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);

    hItem=WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
    WIDGET_AndState(hItem,WIDGET_STATE_FOCUSSABLE);
    
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);
    DROPDOWN_AddString(hItem, Monitor);
    DROPDOWN_AddString(hItem, Copy);
    DROPDOWN_AddString(hItem, ReadModule);
    DROPDOWN_AddString(hItem, "33");
    DROPDOWN_AddString(hItem, "44");
    DROPDOWN_AddString(hItem, "55");
    DROPDOWN_AddString(hItem, "66");
    DROPDOWN_AddString(hItem, "77");
    DROPDOWN_AddString(hItem, "88");
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetAutoScrollV(hItem,1);
    MULTIEDIT_SetWrapWord(hItem);//启用自动换行
    MULTIEDIT_SetReadOnly(hItem,1);//只读模式
    //
    // Initialization of 'Multiedit'
    //
   // hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_1);
   // MULTIEDIT_SetAutoScrollV(hItem,1);


}




/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  u32     dropdown_sel_num;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Dropdown'
    //
    _init_dialog(pMsg);
    GUI_UC_SetEncodeUTF8();    
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) 
    {

    }
    break;
  case WM_MSG_CLOSE:
    WM_DeleteWindow(g_hWin_WaveCarrior);
	break;
  case WM_KEY:
    if((((WM_KEY_INFO*)(pMsg->Data.p))->PressedCnt)==0)//按键释放。added on 2015.1.4
    {
        switch(((WM_KEY_INFO *)(pMsg->Data.p))->Key)
        {
            case GUI_KEY_YELLOW:
                WM_DeleteWindow(g_hWin_WaveCarrior);
                g_hWin_WaveCarrior=0;
                WM_SetFocus(g_hWin_menu);
                break;
            case GUI_KEY_F1:
                ButtonBlink(pMsg,ID_BUTTON_0);
                break;
            case GUI_KEY_F2:
                ButtonBlink(pMsg,ID_BUTTON_3);
                hItem=WM_GetDialogItem(g_hWin_WaveCarrior,ID_DROPDOWN_0);
                dropdown_sel_num=DROPDOWN_GetSel(hItem);
                switch(dropdown_sel_num)
                {
                    case 0:
                        // g_send_para_pkg.g_dst_addr
                        g_send_para_pkg.cmdType = PLC_CMD_TYPE_R2L;
                        g_sys_control.guiState = GUI_PLC_MSG_SET;                        
                        OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                        break;
                     case 1:
                       // g_send_para_pkg.g_dst_addr
                        g_send_para_pkg.cmdType = PLC_CMD_TYPE_L2R;
                        g_sys_control.guiState = GUI_PLC_MSG_SET;
                        OSMboxPost(g_sys_control.downMb, (void*)&g_send_para_pkg);
                        break;
                }
                
                break;
        }
    }
    break;
    
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateWaveCarriorSet
*/
WM_HWIN CreateWaveCarriorSet(void);
WM_HWIN CreateWaveCarriorSet(void) {
  WM_HWIN hWin;
 
  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, g_hWin_menu, 0, 0);
  return hWin;
}










