/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Algerian20.c                                          *
* Font:        Algerian                                              *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 20                                            *
* Range disabled: 0000 - FFFF                                        *
* Character enabled:   0x20 (32)                                     *
* Range enabled:  0020 - 0070                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontAlgerian20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0020[ 20] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0021[ 20] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ________,
  __XX____,
  __XXX___,
  XXXXXX__,
  _XXXXX__,
  _XXXX___,
  __XXX___,
  __XX____,
  __XX____,
  __XX____,
  _XXXX___,
  _XXXX___,
  __XXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0022[ 20] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  XXX_XXX_,
  XXXXXXX_,
  XXXXXXX_,
  XXX_XXX_,
  XXX__XX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0023[ 40] = { /* code 0023, NUMBER SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  ____XX_X,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ___XX_XX,_XX_____,
  _XXXXXXX,XXX_____,
  ___XX_XX,________,
  __XXXXXX,________,
  ___XX_XX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0024[ 40] = { /* code 0024, DOLLAR SIGN */
  ________,________,
  ________,________,
  _____XX_,________,
  _____XX_,________,
  __XXXXXX,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXXXXX_,________,
  _XXXXXX_,________,
  _XXXXXXX,XX______,
  __XXXXXX,XXX_____,
  ____XXXX,XXX_____,
  _XXX_XXX,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,X_______,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0025[ 40] = { /* code 0025, PERCENT SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,________,
  _XXXXXXX,________,
  ____XXXX,XXX_____,
  ____XXXX,XXXX____,
  ___XXXXX,XXXX____,
  __XXX_XX,XXXX____,
  __XXX_XX,XXXX____,
  __XX___X,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0026[ 40] = { /* code 0026, AMPERSAND */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ______XX,XX______,
  _____XXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,XX______,
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  _XXXXX_X,XXX_____,
  __XXXX__,XXXX____,
  ___XXXXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0027[ 20] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXX____,
  _XX_____,
  _XX_____,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0028[ 40] = { /* code 0028, LEFT PARENTHESIS */
  ________,________,
  ________,________,
  _____XX_,________,
  ___XXXXX,________,
  __XXXXXX,________,
  __XXXXX_,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  _XXXXX__,________,
  __XXXX__,________,
  ___XXX__,________,
  __XXXXX_,________,
  ___XXXXX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0029[ 40] = { /* code 0029, RIGHT PARENTHESIS */
  ________,________,
  ________,________,
  _XX_____,________,
  __XXXX__,________,
  ___XXXX_,________,
  ____XXX_,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXXX_,________,
  _XXXXX__,________,
  __XXX___,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002A[ 20] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  _XXXXXX_,
  XXXXXXX_,
  _XXXXXX_,
  __XXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002B[ 40] = { /* code 002B, PLUS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  _XXXXXXX,XX______,
  ____XXX_,XX______,
  _XXXXXXX,XX______,
  ____XXX_,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002C[ 20] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002D[ 20] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXXX__,
  ____XX__,
  _XXXXXX_,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002E[ 20] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  _XXXX___,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_002F[ 40] = { /* code 002F, SOLIDUS */
  ________,________,
  ________,________,
  ________,XX______,
  _______X,XX______,
  _______X,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXX__,________,
  ___XXX__,________,
  __XXX___,________,
  _XXX____,________,
  _XXX____,________,
  XXX_____,________,
  XXX_____,________,
  XX______,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0030[ 40] = { /* code 0030, DIGIT ZERO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXXX_X,XX______,
  XXXXX__X,XXX_____,
  XXXXX__X,XXX_____,
  XXXXX__X,XXX_____,
  XXXXX__X,XXX_____,
  XXXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX_XX,XX______,
  __XXXXXX,XX______,
  ___XXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0031[ 40] = { /* code 0031, DIGIT ONE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0032[ 40] = { /* code 0032, DIGIT TWO */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  _XXXXXXX,XX______,
  _XXXX__X,XXX_____,
  _XXXXX_X,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XX______,
  _____XXX,X_______,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXX___,_XX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0033[ 40] = { /* code 0033, DIGIT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXX__X,XX______,
  __XXXX_X,XX______,
  ____XXXX,X_______,
  ______XX,X_______,
  ____XXXX,XX______,
  __XX___X,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX_XX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0034[ 40] = { /* code 0034, DIGIT FOUR */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXX__,________,
  ___XXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  _XXX_XXX,X_______,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  _____XXX,XXX_____,
  _____XXX,X_______,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0035[ 40] = { /* code 0035, DIGIT FIVE */
  ________,________,
  ________,________,
  ________,________,
  ________,XXX_____,
  __XXXXXX,XXX_____,
  __XX____,_XX_____,
  __XXXXXX,XX______,
  __XXX___,________,
  __XXXXXX,X_______,
  __XXXXXX,XX______,
  ______XX,XXX_____,
  ________,XXX_____,
  _XXXX___,XXX_____,
  _XXXX___,XXX_____,
  __XXXX_X,XX______,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0036[ 40] = { /* code 0036, DIGIT SIX */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XXXXXX,XX______,
  __XXX_XX,XXX_____,
  _XXXXXXX,X_______,
  _XXXX_XX,X_______,
  _XXXXXXX,XX______,
  _XXXX_XX,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  __XXX__X,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XXX_____,
  __XX____,_XX_____,
  __XXXXXX,XXX_____,
  _XXXX___,_XX_____,
  _______X,XX______,
  _______X,XX______,
  ______XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  ________,________,
  ______XX,________,
  ______XX,________,
  ____XXX_,________,
  __XXXXXX,X_______,
  _XXXXXXX,XX______,
  _XXXX__X,XX______,
  _XXXX__X,XX______,
  __XXXXXX,X_______,
  ___XXXXX,X_______,
  __XXXX_X,XXX_____,
  _XXXX___,XXX_____,
  _XXXX___,XXX_____,
  _XXXX___,XXX_____,
  __XXX__X,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0039[ 40] = { /* code 0039, DIGIT NINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,________,
  __XXXXXX,XX______,
  _XXXX__X,XX______,
  _XXXX__X,XXX_____,
  _XXXX__X,XXX_____,
  _XXXX_XX,XXX_____,
  __XXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _______X,XXX_____,
  _______X,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  _XXXXX__,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003A[ 20] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XXXX___,
  __XXX___,
  ________,
  ________,
  ________,
  _XXX____,
  _XXXX___,
  _XXXX___,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003B[ 20] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXXX___,
  _XXXX___,
  __XXX___,
  ________,
  ________,
  ________,
  __XX____,
  _XXXX___,
  _XXXX___,
  _XXX____,
  XXXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003C[ 40] = { /* code 003C, LESS-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _______X,X_______,
  _____XXX,________,
  ____XX__,________,
  __XXX___,________,
  _XXXX___,________,
  __XXXX__,________,
  ____XXXX,________,
  _____XXX,X_______,
  ______XX,X_______,
  _______X,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003D[ 40] = { /* code 003D, EQUALS SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ________,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003E[ 40] = { /* code 003E, GREATER-THAN SIGN */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XX_____,________,
  _XXX____,________,
  __XXXX__,________,
  ___XXXX_,________,
  ____XXXX,X_______,
  ______XX,________,
  ____XXX_,________,
  ___XX___,________,
  __XX____,________,
  _XX_____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_003F[ 40] = { /* code 003F, QUESTION MARK */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXX__,________,
  XXXXXXXX,________,
  XXXXXXXX,X_______,
  XXXXXXXX,X_______,
  _XX_XXXX,X_______,
  ___XXXXX,________,
  __XXXXX_,________,
  __XXX___,________,
  __XXX___,________,
  __XXXX__,________,
  __XXXX__,________,
  ___XXX__,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0040[ 40] = { /* code 0040, COMMERCIAL AT */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXX____,
  _XXXXXXX,XXX_____,
  __XXX___,________,
  ___XXXXX,XXXX____,
  ____XXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0041[ 40] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,XX______,
  ____XXXX,XX______,
  __XXXXXX,XXXX____,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXX__,_XXXX___,
  _XXXXX__,_XXXX___,
  XXXXXX__,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0042[ 40] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XX______,
  _XXXXXXX,XXXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXXX____,
  _XXXXXXX,XX______,
  __XXXXXX,XXXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0043[ 40] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XX______,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,XX______,
  XXXXX___,XXX_____,
  _XXXXX__,XXX_____,
  __XXXX_X,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0044[ 40] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0045[ 40] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXXX_X,XX______,
  __XXXX_X,X_______,
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXXXX,________,
  __XXXX__,_XX_____,
  __XXXX__,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0046[ 40] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  __XXXX_X,XX______,
  __XXXXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXXXX_,________,
  XXXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0047[ 40] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_XX____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XXX_____,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXX___,XXX_____,
  _XXXX___,XXX_____,
  __XXXX__,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0048[ 40] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXX_X,XXXX____,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0049[ 20] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXXXX__,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004A[ 40] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _XX__XXX,X_______,
  XXXX_XXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004B[ 40] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  __XXXX__,XXX_____,
  __XXXX_X,XX______,
  __XXXX_X,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,XX______,
  __XXXX_X,XX______,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  _XXXXX__,XXXX____,
  _XXXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004C[ 40] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,XX______,
  __XXXX__,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004D[ 40] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,XXXXX___,
  __XXXX__,_XXXXX__,
  __XXXXX_,XXXXX___,
  __XXXXX_,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,_XXXX___,
  _XXXX_XX,_XXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004E[ 40] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  __XXXX__,XX______,
  __XXXXX_,XX______,
  __XXXXX_,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXX_XX,XX______,
  __XXX_XX,XX______,
  __XXX__X,XX______,
  _XXXXX_X,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_004F[ 40] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXX__,XXX_____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  _XXXX__X,XXXX____,
  _XXXX__X,XXX_____,
  ___XXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0050[ 40] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX_X,XXXX____,
  _XXXXXXX,XX______,
  XXXXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0051[ 40] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_______,
  __XXXX_X,XXX_____,
  _XXXX__X,XXX_____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXXXX_,XXX_____,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  ___XXXXX,XXXXX___,
  ________,XXXX____,
  ________,__XX____,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0052[ 40] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,X_______,
  _XXXXXXX,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX_X,XXX_____,
  __XXXXXX,XX______,
  _XXXX_XX,X_______,
  __XXXXXX,X_______,
  __XXXX_X,XX______,
  __XXXX__,XXX_____,
  _XXXXX__,XXXX____,
  _XXXXXX_,XXXX____,
  ______XX,XXXX____,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0053[ 40] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __XXXXXX,XX______,
  _XXXX_XX,XX______,
  _XXXX_XX,X_______,
  _XXX____,________,
  _XXXXX__,________,
  _XXXXXXX,X_______,
  __XXX_XX,XXX_____,
  ____XXXX,XXX_____,
  _XX____X,XXX_____,
  _XXX__XX,XXX_____,
  XXXXXXXX,XX______,
  XXXXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0054[ 40] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  _XX_XXX_,_XX_____,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ____XXX_,________,
  ___XXXXX,________,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0055[ 40] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  ___XXXXX,XX______,
  __XXXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0056[ 40] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,________,
  ________,___X____,
  ________,_XXX____,
  ________,XXXX____,
  XXXXX___,_XXX____,
  _XXXX___,XXX_____,
  _XXXX___,XXX_____,
  __XXX___,XX______,
  __XXXX_X,XX______,
  ___XXX_X,X_______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0057[ 40] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,________,
  ________,______X_,
  ________,____XXX_,
  ________,___XXXX_,
  XXXXX__X,XX__XXX_,
  _XXXX_XX,XX__XX__,
  _XXXX_XX,XX_XXX__,
  _XXXX_XX,XX_XXX__,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  ___XXXX_,XXXXX___,
  ___XXXX_,XXXX____,
  ___XXXX_,_XXX____,
  ___XXXX_,XXXXX___,
  __XXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0058[ 40] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  ___XXX__,XXXXX___,
  ___XXXXX,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ___XXXXX,XX______,
  ___XX__X,XXX_____,
  __XXX__X,XXX_____,
  XXXXX__X,XXXX____,
  XXXXXX_X,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0059[ 40] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,________,
  ________,___XX___,
  ________,XXXXX___,
  ________,_XXX____,
  XXXXX___,_XXX____,
  _XXXX___,XXX_____,
  _XXXX__X,XX______,
  __XXXX_X,XX______,
  ___XXXXX,X_______,
  ___XXXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXXX,X_______,
  __XXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005A[ 40] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  __XX__XX,XX______,
  ______XX,X_______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,XXX_____,
  _XXXX___,XXX_____,
  _XXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005B[ 40] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,________,
  ________,________,
  ________,________,
  __XXXXX_,________,
  __XXXXXX,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXXXX,________,
  __XXXXXX,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005C[ 40] = { /* code 005C, REVERSE SOLIDUS */
  ________,________,
  ________,________,
  X_______,________,
  XX______,________,
  XXX_____,________,
  _XX_____,________,
  _XXX____,________,
  __XX____,________,
  ___XX___,________,
  ___XXX__,________,
  ____XX__,________,
  ____XXX_,________,
  _____XX_,________,
  _____XXX,________,
  ______XX,X_______,
  _______X,X_______,
  _______X,XX______,
  ________,XX______,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005D[ 40] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  _XXXXXX_,________,
  _XXXXXX_,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005E[ 40] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,________,
  ________,________,
  ________,________,
  ____XX__,________,
  ____XXX_,________,
  ___XXXX_,________,
  __XXXXXX,________,
  __XXX_XX,________,
  _XXXX__X,X_______,
  XXXX____,XX______,
  XXX_____,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_005F[ 40] = { /* code 005F, LOW LINE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,XX______,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0060[ 40] = { /* code 0060, GRAVE ACCENT */
  __XXX___,________,
  ___XXX__,________,
  ____XXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0061[ 40] = { /* code 0061, LATIN SMALL LETTER A */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,XX______,
  ____XXXX,XX______,
  __XXXXXX,XXXX____,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  __XXXX__,_XXXX___,
  _XXXXX__,_XXXX___,
  XXXXXX__,XXXXXXX_,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0062[ 40] = { /* code 0062, LATIN SMALL LETTER B */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XX______,
  _XXXXXXX,XXXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXXX____,
  _XXXXXXX,XX______,
  __XXXXXX,XXXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0063[ 40] = { /* code 0063, LATIN SMALL LETTER C */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,XXX_____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XX______,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,________,
  XXXXX___,XX______,
  XXXXX___,XXX_____,
  _XXXXX__,XXX_____,
  __XXXX_X,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0064[ 40] = { /* code 0064, LATIN SMALL LETTER D */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXX__,XXX_____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,_XXX____,
  __XXXX__,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXXXX,XX______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0065[ 40] = { /* code 0065, LATIN SMALL LETTER E */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  __XXXXXX,XXX_____,
  __XXXX_X,XX______,
  __XXXX_X,X_______,
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXXXX,________,
  __XXXX__,_XX_____,
  __XXXX__,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0066[ 40] = { /* code 0066, LATIN SMALL LETTER F */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXX_____,
  __XXXXXX,XX______,
  __XXXX_X,XX______,
  __XXXXXX,________,
  __XXXXXX,X_______,
  _XXXXXXX,X_______,
  XXXXXXXX,X_______,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXXXX_,________,
  XXXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0067[ 40] = { /* code 0067, LATIN SMALL LETTER G */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_XX____,
  __XXXXXX,XXX_____,
  _XXXXX_X,XXX_____,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXX___,XXX_____,
  _XXXX___,XXX_____,
  __XXXX__,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0068[ 40] = { /* code 0068, LATIN SMALL LETTER H */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXXXX,XXX_____,
  XXXXXXXX,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  __XXXX_X,XXX_____,
  _XXXXX_X,XXXX____,
  _XXXXXXX,XXXX____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0069[ 20] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  ________,
  _XXXXX__,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  __XXX___,
  _XXXXX__,
  XXXXXX__,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006A[ 40] = { /* code 006A, LATIN SMALL LETTER J */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _____XXX,X_______,
  _XX__XXX,X_______,
  XXXX_XXX,X_______,
  XXXXXXXX,X_______,
  XXXXXXXX,XX______,
  _XXXXXXX,X_______,
  _XXXXXXX,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006B[ 40] = { /* code 006B, LATIN SMALL LETTER K */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXXX___,
  __XXXX__,XXX_____,
  __XXXX_X,XX______,
  __XXXX_X,X_______,
  __XXXXXX,X_______,
  __XXXXXX,X_______,
  __XXXXXX,XX______,
  __XXXX_X,XX______,
  __XXXX__,XXX_____,
  __XXXX__,XXX_____,
  _XXXXX__,XXXX____,
  _XXXXXXX,XXXXX___,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006C[ 40] = { /* code 006C, LATIN SMALL LETTER L */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,XX______,
  __XXXX__,XXX_____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006D[ 40] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXX_,XXXXX___,
  __XXXX__,_XXXXX__,
  __XXXXX_,XXXXX___,
  __XXXXX_,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,XXXXX___,
  __XXXXXX,_XXXX___,
  _XXXX_XX,_XXXXX__,
  XXXXXXXX,XXXXXX__,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006E[ 40] = { /* code 006E, LATIN SMALL LETTER N */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,XXXX____,
  __XXXX__,XX______,
  __XXXXX_,XX______,
  __XXXXX_,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXXXXX,XX______,
  __XXX_XX,XX______,
  __XXX_XX,XX______,
  __XXX__X,XX______,
  _XXXXX_X,XX______,
  XXXXXXXX,XX______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_006F[ 40] = { /* code 006F, LATIN SMALL LETTER O */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ___XXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXX__,XXX_____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  XXXXX___,XXXX____,
  _XXXX__X,XXXX____,
  _XXXX__X,XXX_____,
  ___XXXXX,XX______,
  ___XXXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontAlgerian20_0070[ 40] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _XXXXXXX,X_______,
  __XXXXXX,XXXX____,
  __XXXX__,XXXX____,
  __XXXX__,XXXX____,
  __XXXX_X,XXXX____,
  _XXXXXXX,XX______,
  XXXXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXXX__,________,
  _XXXXXX_,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontAlgerian20_CharInfo[81] = {
   {   6,   6,  1, acGUI_FontAlgerian20_0020 } /* code 0020 */
  ,{   7,   7,  1, acGUI_FontAlgerian20_0021 } /* code 0021 */
  ,{   7,   7,  1, acGUI_FontAlgerian20_0022 } /* code 0022 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0023 } /* code 0023 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0024 } /* code 0024 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0025 } /* code 0025 */
  ,{  15,  15,  2, acGUI_FontAlgerian20_0026 } /* code 0026 */
  ,{   4,   4,  1, acGUI_FontAlgerian20_0027 } /* code 0027 */
  ,{   9,   9,  2, acGUI_FontAlgerian20_0028 } /* code 0028 */
  ,{   9,   9,  2, acGUI_FontAlgerian20_0029 } /* code 0029 */
  ,{   7,   7,  1, acGUI_FontAlgerian20_002A } /* code 002A */
  ,{  12,  12,  2, acGUI_FontAlgerian20_002B } /* code 002B */
  ,{   6,   6,  1, acGUI_FontAlgerian20_002C } /* code 002C */
  ,{   7,   7,  1, acGUI_FontAlgerian20_002D } /* code 002D */
  ,{   6,   6,  1, acGUI_FontAlgerian20_002E } /* code 002E */
  ,{  10,  10,  2, acGUI_FontAlgerian20_002F } /* code 002F */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0030 } /* code 0030 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0031 } /* code 0031 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0032 } /* code 0032 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0033 } /* code 0033 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0034 } /* code 0034 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0035 } /* code 0035 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0036 } /* code 0036 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0037 } /* code 0037 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0038 } /* code 0038 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0039 } /* code 0039 */
  ,{   6,   6,  1, acGUI_FontAlgerian20_003A } /* code 003A */
  ,{   6,   6,  1, acGUI_FontAlgerian20_003B } /* code 003B */
  ,{  10,  10,  2, acGUI_FontAlgerian20_003C } /* code 003C */
  ,{  12,  12,  2, acGUI_FontAlgerian20_003D } /* code 003D */
  ,{  10,  10,  2, acGUI_FontAlgerian20_003E } /* code 003E */
  ,{   9,   9,  2, acGUI_FontAlgerian20_003F } /* code 003F */
  ,{  14,  14,  2, acGUI_FontAlgerian20_0040 } /* code 0040 */
  ,{  15,  15,  2, acGUI_FontAlgerian20_0041 } /* code 0041 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0042 } /* code 0042 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0043 } /* code 0043 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0044 } /* code 0044 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0045 } /* code 0045 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0046 } /* code 0046 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0047 } /* code 0047 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0048 } /* code 0048 */
  ,{   7,   7,  1, acGUI_FontAlgerian20_0049 } /* code 0049 */
  ,{  10,  10,  2, acGUI_FontAlgerian20_004A } /* code 004A */
  ,{  13,  13,  2, acGUI_FontAlgerian20_004B } /* code 004B */
  ,{  11,  11,  2, acGUI_FontAlgerian20_004C } /* code 004C */
  ,{  14,  14,  2, acGUI_FontAlgerian20_004D } /* code 004D */
  ,{  12,  12,  2, acGUI_FontAlgerian20_004E } /* code 004E */
  ,{  12,  12,  2, acGUI_FontAlgerian20_004F } /* code 004F */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0050 } /* code 0050 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0051 } /* code 0051 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0052 } /* code 0052 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0053 } /* code 0053 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0054 } /* code 0054 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0055 } /* code 0055 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0056 } /* code 0056 */
  ,{  15,  15,  2, acGUI_FontAlgerian20_0057 } /* code 0057 */
  ,{  14,  14,  2, acGUI_FontAlgerian20_0058 } /* code 0058 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0059 } /* code 0059 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_005A } /* code 005A */
  ,{   9,   9,  2, acGUI_FontAlgerian20_005B } /* code 005B */
  ,{  10,  10,  2, acGUI_FontAlgerian20_005C } /* code 005C */
  ,{   9,   9,  2, acGUI_FontAlgerian20_005D } /* code 005D */
  ,{  10,  10,  2, acGUI_FontAlgerian20_005E } /* code 005E */
  ,{  10,  10,  2, acGUI_FontAlgerian20_005F } /* code 005F */
  ,{  10,  10,  2, acGUI_FontAlgerian20_0060 } /* code 0060 */
  ,{  15,  15,  2, acGUI_FontAlgerian20_0061 } /* code 0061 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0062 } /* code 0062 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0063 } /* code 0063 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0064 } /* code 0064 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0065 } /* code 0065 */
  ,{  11,  11,  2, acGUI_FontAlgerian20_0066 } /* code 0066 */
  ,{  13,  13,  2, acGUI_FontAlgerian20_0067 } /* code 0067 */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0068 } /* code 0068 */
  ,{   7,   7,  1, acGUI_FontAlgerian20_0069 } /* code 0069 */
  ,{  10,  10,  2, acGUI_FontAlgerian20_006A } /* code 006A */
  ,{  13,  13,  2, acGUI_FontAlgerian20_006B } /* code 006B */
  ,{  11,  11,  2, acGUI_FontAlgerian20_006C } /* code 006C */
  ,{  14,  14,  2, acGUI_FontAlgerian20_006D } /* code 006D */
  ,{  12,  12,  2, acGUI_FontAlgerian20_006E } /* code 006E */
  ,{  12,  12,  2, acGUI_FontAlgerian20_006F } /* code 006F */
  ,{  12,  12,  2, acGUI_FontAlgerian20_0070 } /* code 0070 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontAlgerian20_Prop1 = {
   0x0020 /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontAlgerian20_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontAlgerian20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontAlgerian20_Prop1}
  ,16 /* Baseline */
  ,12 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

